### PR TITLE
Add YumListInstalled Parser

### LINKED ISSUE #1854: Add "reponame" to the rpm query string for InstalledRpms
There's no way to connect the rpm information in `InstalledRpms` to the `YumReposD` information. Adding the `reponame` field to the rpms would provide a link between them.

### PR DESCRIPTION
**Pull request by csams**
Adds a new parser, `YumListInstalled`, that shares an interface with `InstalledRpms` but uses the output of `yum list installed` instead of `rpm`. It produces `YumInstalledRpm` instances, which are subclass instances of `InstalledRpm` with a `.repo` attribute to hold the originating yum repo name.

Fixes #1854 , although I still need an addition to the uploader.json.

### CODE REVIEW

**Comment by bfahr** [comment]
Waiting on further analysis to merge this PR.

**Comment by Rezney** [comment]
@csams  would it be possible to get also repo info with `YumListInstalled.packages` ?

**Comment by lhuett** [comment]
@Rezney Is something like this[6] what you are asking about?
In [4]: YumListInstalled.get_max('bash')                                                                                                                                                      
Out[4]: 0:bash-4.4.23-1.fc28
rpm = YumListInstalled.get_max('bash')
In [6]: rpm.repo                                                                                                                                                                              
Out[6]: 'updates'

**Comment by Rezney** [comment]
@lhuett I actually meant "InstalledRpms.packages" dict but I realized I do not need it. The way you showed is pretty fine. Sorry for the fuss...

**Pull request merged**
