### PR TITLE
feat: add CloudInstance to canonical_facts

### PR DESCRIPTION
**Pull request by xiangce**
Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Complete Description of Additions/Changes:

- Add the CloudInstance and OSRelease for puptoo (Advisor UI)
- for details see ESSNTL-3114 (for CloundInstance)

### CODE REVIEW

**Comment by xiangce** [comment]
@bfahr and @ryan-blakley - please ignore this PR for now, I made a mistake, and it may be not required.

**Comment by xiangce** [comment]
[Update] I'm asking Rodrigo Antunes to confirm if this change works for him.

**Comment by xiangce** [comment]
@bfahr, @ryan-blakley @chenlizhong  - This PR is still required per the ESSNTL-3114, please have a look.

**Review by chenlizhong — APPROVED** [review]
Looks good to me

**Review by bfahr — APPROVED** [review]
Looks good to me @xiangce

**Pull request merged**
