### PR TITLE
fix: fix processing of SerializedArchiveContext

### LINKED ISSUE #3158: The validation of ContextProvider for core collection failed
For the `insights-archive` collected by the new Core Collection identified by the `"insights_archive.txt"`, the path of the real collected data is placed in the './data' but not the './' which works for the old archives.

It always reports the following error when `insights-run` against a new archive:

```

Traceback (most recent call last):
  File "/Users/liuxc/work/insights/insights-core/insights/core/plugins.py", line 90, in invoke
    return self.component(broker)
  File "/Users/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 569, in __call__
    return self.kind(ctx.locate_path(self.path), root=ctx.root, ds=self, ctx=ctx)
  File "/Users/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 175, in __init__
    self.validate()
  File "/Users/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 183, in validate
    raise ContentException("%s does not exist." % self.path)
insights.core.plugins.ContentException: /private/tmp/insights-ip-172-31-21-63.us-east-2.compute.internal-20210713080914/etc/redhat-release does not exist.
```

But in fact, the file is placed at 
```
insights-ip-172-31-21-63.us-east-2.compute.internal-20210713080914/data/etc/redhat-release
```

### PR DESCRIPTION
**Pull request by bfahr**
### All Pull Requests:

Check all that apply:

* [X] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [X] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:
* When core collection archives are hydrated the broker is prepopulated
  with all data defined in the ./meta_data subdir. Since the specs are
  already loaded there is no need to collect them again from the
  archive.  The only datasources that need to be collected are those not defined
  in the ./meta_data subdir, and those are in the / dir, not /data.
* This change removes datasources from the graph where specs are already
  hydrated in the broker before running.
* Fix #3158

Signed-off-by: Bob Fahr <20520336+bfahr@users.noreply.github.com>

### CODE REVIEW

**Comment by skontar** [comment]
I have tested the behavior and it seems that it is correct.

**Comment by xiangce** [comment]
@bfahr and @ryan-blakley, Hi, I did a bit of modification based on Bob's patch, now the Exceptions from core-collected archive look like:
```
Traceback (most recent call last):
  File "/home/liuxc/work/insights/insights-core/insights/core/plugins.py", line 98, in invoke
    return self.component(broker)
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 615, in __call__
    return self.kind(ctx.locate_path(self.path), root=ctx.root, ds=self, ctx=ctx)
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 141, in __init__
    self.validate()
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 191, in validate
    super(MetadataProvider, self).validate()
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 149, in validate
    raise ContentException("%s does not exist." % self.path)
insights.core.exceptions.ContentException: /tmp/insights/soscleaner-core_1/tags.json does not exist.

Traceback (most recent call last):
  File "/home/liuxc/work/insights/insights-core/insights/core/plugins.py", line 98, in invoke
    return self.component(broker)
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 615, in __call__
    return self.kind(ctx.locate_path(self.path), root=ctx.root, ds=self, ctx=ctx)
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 141, in __init__
    self.validate()
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 149, in validate
    raise ContentException("%s does not exist." % self.path)
insights.core.exceptions.ContentException: /tmp/insights/soscleaner-core_1/data/var/lib/pacemaker/cib/cib.xml does not exist
```

And Exceptions from legacy collection look like:
```
Traceback (most recent call last):
  File "/home/liuxc/work/insights/insights-core/insights/core/plugins.py", line 98, in invoke
    return self.component(broker)
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 615, in __call__
    return self.kind(ctx.locate_path(self.path), root=ctx.root, ds=self, ctx=ctx)
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 141, in __init__
    self.validate()
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 191, in validate
    super(MetadataProvider, self).validate()
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 149, in validate
    raise ContentException("%s does not exist." % self.path)
insights.core.exceptions.ContentException: /tmp/insights/soscleaner-legacy_1/tags.json does not exist.


Traceback (most recent call last):
  File "/home/liuxc/work/insights/insights-core/insights/core/plugins.py", line 98, in invoke
    return self.component(broker)
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 615, in __call__
    return self.kind(ctx.locate_path(self.path), root=ctx.root, ds=self, ctx=ctx)
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 141, in __init__
    self.validate()
  File "/home/liuxc/work/insights/insights-core/insights/core/spec_factory.py", line 149, in validate
    raise ContentException("%s does not exist." % self.path)
insights.core.exceptions.ContentException: /tmp/insights/soscleaner-legacy_1/var/lib/pacemaker/cib/cib.xml does not exist.
```

Please kindly review.

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
test me

**Pull request merged**
