### PR TITLE
[YumLog] Add filter

### PR DESCRIPTION
**Pull request by psachin**
Signed-off-by: Sachin Patil <psachin@redhat.com>

### CODE REVIEW

**Comment by xiangce** [comment]
Relates to #2182 #2180.

@psachin - Please point out the problem you are trying to resolve/fix.

**Comment by psachin** [comment]
@xiangce The changes are needed for one of the plugin.

**Comment by xiangce** [comment]
> @xiangce The changes are needed for one of the plugin.

Does not the current parser w/o `filterable=Ture` work for the plugin? I believe that there are reasons for this parser is designed filterable originally, although it's hard to trace.
However, I think it's OK to make it filterable for bug-fixing or removing sensitive data, please provide the evidence for that since the change changes the original API.

**Comment by psachin** [comment]
Hey @xiangce  Sorry to miss your reply. With the recent change in plugin logic, this change is not required any more.

> Does not the current parser w/o filterable=Ture work for the plugin? I believe that there are reasons for this parser is designed filterable originally, although it's hard to trace.

Same here. I was not able to find any hints to why this parser is not having `filterable=True`

> However, I think it's OK to make it filterable for bug-fixing or removing sensitive data, please provide the evidence for that since the change changes the original API.

By making it filterable, the plugin can leverage attributes such as `keep_scan`, `token_scan` etc. 

Let us close this for now, we can re-open for review if there's a future requirement.

**Pull request closed without merging**
