### PR TITLE
Soscleaner fix

### PR DESCRIPTION
**Pull request by Glutexo**
### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

*Add your description here*

### CODE REVIEW

**Comment by ahitacat** [comment]
This LGTM, once the flake8 is fixed :smile: I have manually test it and can resolve the IP Obfuscation problem.

**Review by ahitacat — CHANGES_REQUESTED** [review]
This LGTM, once the flake8 is fixed smile I have manually test it and can resolve the IP Obfuscation problem.

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
test me

**Review by strider — APPROVED** [review]

**Pull request merged**
