### PR TITLE
Update PsAuxcww parser to skip heading warn message

### PR DESCRIPTION
**Pull request by chenlizhong**
#913

### CODE REVIEW

**Comment by bfahr** [comment]
@chenlizhong would you mind to provide more information about the purpose of this PR.  Is it to fix an existing reported issue, if so could you provide a reference to the issue report? Thanks.

**Comment by chenlizhong** [comment]
@bfahr 
I open the issue  https://github.com/RedHatInsights/insights-core/issues/912
If you need more info, let me know.

**Comment by bfahr** [comment]
@chenlizhong thank you for the explanation and thank you for adding the reference to the issue, that is sufficient.

**Comment by chenlizhong** [comment]
@bfahr 
You are experienced!!!
Just test the rules. There is one test data with "UER" no "USER".  I just submit PR to fix it.

**Comment by xiangce** [comment]
3.x is already OK, do not need this patch.

**Pull request merged**
