### PR TITLE
chore(test): Add unit tests for playbook verification 

### PR DESCRIPTION
**Pull request by m-horky**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

This set of commits updates the vendored Ansible playbook verifier to make it more maintainable and testable. It adds unit tests that help describe the expectations of the methods.

### Notes

- There is a known issue making the verification fail on Python 3.12. It is tracked internally as CCT-538.
- The PR has been split into commits for a reason. Please, rebase-merge instead of squash-merging it.

### CODE REVIEW

**Review by subpop — APPROVED** [review]
LGTM

**Comment by m-horky** [comment]
@xiangce Hi, I believe this can be merged. Could you please rebase-merge it so the commits stay separate and we keep the history?

**Comment by xiangce** [comment]
@m-horky - sure things. I enabled the `rebase and merge` temporary and merged this PR in that way. However, as we need to cherry-pick each PR (commits) to the 3.0 branch to release them, the `rebase and merge` feature is not recommended. So I disabled it again.

**Comment by m-horky** [comment]
@xiangce I understand, thank you. This patch has slightly increased regression risk potential, so I wanted the changes to be easy to trace.

**Pull request merged**
