### PR TITLE
Added new Spec for modinfo in sos_archive

### PR DESCRIPTION
**Pull request by crackcodecamp**
Added spec for modinfo files in sos_archive.
`modinfo = glob_file("sos_commands/kernel/modinfo_*")`

### CODE REVIEW

**Comment by crackcodecamp** [comment]
@xiangce Please help to review this MR.

**Comment by xiangce** [comment]
@crackcodecamp  - I found the following kind of files in the sosreport archives:

~~~
❱ ls sosreport-DutyOSS.01950525-20171015064632/sos_commands/kernel/modinfo_*
sosreport-DutyOSS.01950525-20171015064632/sos_commands/kernel/modinfo_tpm_tpm_tis_libata_efivars_tcp_cubic_kernel_printk_kgdb_spurious_pstore_dynamic_debug_pcie_aspm_pci_hotplug_pciehp_acpiphp_intel_idle_acpi_pci_slot_processor_thermal_acpi_memhotplug_battery_keyboard_vt_8250_kgdboc_kgdbts_scsi_mod_pcmcia_core_pcmci

❱ ls sosreport-silverdc1-02344573-2019-03-25-qbgwlyf/sos_commands/kernel/modinfo_*
sosreport-silverdc1-02344573-2019-03-25-qbgwlyf/sos_commands/kernel/modinfo_ALL_MODULES
~~~

But the current parser of ModinfoEach is for single module-info file, e.g. `modinfo pcmci`, it will get an incorrect parser result when applying to the merged file, e.g `modinfo_ALL_MODULES`.

I'll raise an issue for this problem, and merge this PR after that issue is fixed.

**Comment by xiangce** [comment]
@crackcodecamp  - I found the following kind of files in the sosreport archives:

~~~
❱ ls sosreport-DutyOSS.01950525-20171015064632/sos_commands/kernel/modinfo_*
sosreport-DutyOSS.01950525-20171015064632/sos_commands/kernel/modinfo_tpm_tpm_tis_libata_efivars_tcp_cubic_kernel_printk_kgdb_spurious_pstore_dynamic_debug_pcie_aspm_pci_hotplug_pciehp_acpiphp_intel_idle_acpi_pci_slot_processor_thermal_acpi_memhotplug_battery_keyboard_vt_8250_kgdboc_kgdbts_scsi_mod_pcmcia_core_pcmci

❱ ls sosreport-silverdc1-02344573-2019-03-25-qbgwlyf/sos_commands/kernel/modinfo_*
sosreport-silverdc1-02344573-2019-03-25-qbgwlyf/sos_commands/kernel/modinfo_ALL_MODULES
~~~

But the current parser of ModinfoEach is for single module-info file, e.g. `modinfo pcmci`, it will get an incorrect parser result when applying to the merged file, e.g `modinfo_ALL_MODULES`.

I'll raise an issue for this problem, and merge this PR after that issue is fixed.

**Comment by xiangce** [comment]
@crackcodecamp - I have raised another PR to fix #2220 and have also added the `modinfo_all` spec into the sos_archive.py. Would you please to have a look and close this PR? Thanks.

**Comment by bfahr** [comment]
Closing since this was implemented by #2236.

**Pull request closed without merging**
