### PR TITLE
fix: handle empty value in krb5 config

### PR DESCRIPTION
**Pull request by JoySnow**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] No Sensitive Data in this change?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

See the following line in Errors report: 
| count| component| request_id| exception|
| -------- | ------- | -------- | ------- |
|33315| insights.parsers.krb5.Krb5Configuration|a9bd78cbb38e4c438e5f0e9c3b9eb57e| IndexError('list index out of range')|

An example input of this `Krb5Configuration`: 
```
[libdefaults]
permitted_enctypes =  
```

To proper handle such content in parser `Krb5Configuration`.  

RHINENG-14573

### CODE REVIEW

**Comment by JoySnow** [comment]
@wushiqinlou Could you help confirm if the handling for this special case work?

**Comment by wushiqinlou** [comment]
@JoySnow - LGTM

**Review by xiangce — CHANGES_REQUESTED** [review]
Your new change looks good, but I believe the old L133 should also be updated in the same.

**Comment by xiangce** [comment]
@JoySnow - Better add a test for the case when `is_squ=True`

**Comment by JoySnow** [comment]
@xiangce Updated accordingly.

**Pull request merged**
