### PR TITLE
fix: update ubuntu image

### PR DESCRIPTION
**Pull request by ahitacat**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

Updated ubuntu image

### CODE REVIEW

**Comment by mhuth** [comment]
*sigh* why are we using Ubuntu images and not Red Hat? :cry:

**Comment by subpop** [comment]
> _sigh_ why are we using Ubuntu images and not Red Hat? cry

I've wondered about this too, but I'd say that change should be a separate PR from this one. This one is about fixing a broken test. We could explore the idea of switching to UBI images or CentOS Stream images in another PR.

**Comment by tiran** [comment]
* `test_with_zip` seems to fail because the `unzip` binary is not installed
* `test_magic_plan_b` fails to load the `magic_open` C function pointer from libmagic with ctypes. This might be a problem with libmagic, ctypes, or libffi.
* The `test_oscap_*` seems to fail because it cannot find `rpm` binary (Ubuntu?).

**Comment by ahitacat** [comment]
I'm closing this PR as it was continued in https://github.com/RedHatInsights/insights-core/pull/3766

**Pull request closed without merging**
