### PR TITLE
Fix issues with in ceph version parser.

### PR DESCRIPTION
**Pull request by ashishkumsingh**
Fixed the regex issue in the 'ceph_version.py' parser file.
Also updated the community_to_release_map to add new Ceph release.

Signed-off-by: Ashish Singh <assingh@redhat.com>

### CODE REVIEW

**Comment by shzhou12** [comment]
@ashishkumsingh  Could you please add a test case for the modification?

**Comment by ashishkumsingh** [comment]
> @ashishkumsingh Could you please add a test case for the modification?

Added the test case for version `12.2.8-128.el7cp`.

**Comment by shzhou12** [comment]
@xiangce The code looks good to me, could you please double check?

**Comment by xiangce** [comment]
@ashishkumsingh - The test failed for below exception, please have a check:
~~~
>       ceph = CephVersion(context_wrap(CV_5))

...

        pattern_community = r'((\d{1,2})\.(\d{1,2})\.((\d{1,2})|x))((\-(\d+)))'
        community_version_mo = re.search(pattern_community, str(ceph_version_line), 0)
        if not community_version_mo:
>           raise CephVersionError("Wrong Format Ceph Version", content)
E           insights.parsers.ceph_version.CephVersionError: Wrong Format Ceph Version
~~~

**Comment by ashishkumsingh** [comment]
@shzhou12 @xiangce The test file is actually incorrect.

The test for `CV_5` is mentioning an incorrect Ceph version.
-----
CV_5 = "ceph version 10.2.5 (c461ee19ecbc0c5c330aca20f7392c9a00730367)"
...
   ceph = CephVersion(context_wrap(CV_5))
    assert ceph.version == "2.2"
    assert ceph.major == '2'
    assert ceph.minor == '2'
    assert ceph.downstream_release == "0"
-----

Howeve, the complete version for RHCS 2.2 is `10.2.5-37.el7cp` and not `10.2.5`.

**Comment by shzhou12** [comment]
@ashishkumsingh Looks good to me.

**Comment by xiangce** [comment]
@ashishkumsingh - Thanks for pointing that out.

@psachin - the test case `CV_5` is added by you (https://github.com/RedHatInsights/insights-core/commit/518da6e), please double confirm.

**Pull request merged**
