### PR TITLE
Use /var/tmp/insights-client for egg release

### PR DESCRIPTION
**Pull request by Glutexo**
Instead of fetching the egg release file to a world-writable _/tmp_ directory, use _/var/tmp/insights-client_ instead. This directory is not accessible by any other user than the owner. Tampering with the egg release file by regular users is no longer possible. If the _/var/tmp/insights-client_ is not present, it is created.

It is still possible for a non-root user to prevent fetching the file. If _/var/tmp/insights-client_ does not exist beforehand and a non-root user creates it while _/var/tmp_ having a sticky bit set, _write_data_to_file_ would cause the fetch to not be able to save the file. This has been already possible before, so it did not become worse.

### CODE REVIEW

**Comment by Glutexo** [comment]
Checks passed! 🎉 
Asking for a review, @subpop or @gravitypriest.

**Review by gravitypriest — APPROVED** [review]

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by gravitypriest** [comment]
One QE test failure re: ultralight checkin, unrelated to this PR

**Comment by Glutexo** [comment]
Yay!!

**Pull request merged**
