### PR TITLE
Enhance MountEntry and MountOpts of parser mount

### PR DESCRIPTION
**Pull request by JoySnow**
Use self._date over self.date to keep data as private.
      Use __getattr__ and __setattr__ for attr access from self._data,
      and protect from attr writing in customer usage.
      Add MountEntry.data property for backwards-compatibility usage.

### CODE REVIEW

**Comment by JoySnow** [comment]
Resolve https://github.com/RedHatInsights/insights-core/issues/2081

**Comment by JoySnow** [comment]
Fix https://github.com/RedHatInsights/insights-core/issues/2081

**Comment by xiangce** [comment]
@JoySnow - Maybe the https://github.com/RedHatInsights/insights-core/pull/2070/commits/fbd53e8698409485e982bad8a7958a6c6b490c06 could cover this.

**Comment by JoySnow** [comment]
Close for duplicate implement/fix of https://github.com/RedHatInsights/insights-core/issues/2081 .

**Pull request closed without merging**
