### PR TITLE
Remove subscription_manager_repos_list_enabled from insights_archive.py

### PR DESCRIPTION
**Pull request by xiangce**
- No plugins use this spec for now
- Will remove it from the uploader.json as well

### CODE REVIEW

**Comment by xiangce** [comment]
Please do not review or merge it, further analysis is needed for this PR.

**Comment by xiangce** [comment]
Since this Parser is not used by any rules, and the spec is not collected by sosreport too, I removed the parser as well, please have a check @bfahr . Thanks.

**Comment by bfahr** [comment]
@xiangce this PR has some conflicts now that we merged a couple of the other subscription manager PRs.  Would you mind to fix them?

**Comment by xiangce** [comment]
@bfahr, Thanks, I will resolve the conflicts then merge it today.

**Pull request merged**
