### PR TITLE
Add release timeline

### PR DESCRIPTION
**Pull request by psachin**
The guidelines, examples and the release timeline will help developers to plan the function
deprecation w.r.t the insights-core release cycle.

Signed-off-by: Sachin Patil <psachin@redhat.com>

### All Pull Requests:

Check all that apply:

* [X] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

*Add your description here*

### CODE REVIEW

**Review by bfahr — APPROVED** [review]

**Review by xiangce — APPROVED** [review]
Good to me.

BTW, per Bob's suggestion, please use the [Conversional commit](https://www.conventionalcommits.org/en/v1.0.0/) for insights-core

**Comment by psachin** [comment]
@xiangce I have included the description in the beginning of the commit message.

**Review by ryan-blakley — APPROVED** [review]
Looks good to me.

**Comment by xiangce** [comment]
> @xiangce I have included the description in the beginning of the commit message.
[Conversional commit](https://www.conventionalcommits.org/en/v1.0.0/) is not about the description of the PR, it's about `lightweight convention on top of commit messages`, see the
https://www.conventionalcommits.org/en/v1.0.0/ for details.

**Pull request merged**
