### PR TITLE
⚠️ Exclude yum_log from IP obfuscation

### PR DESCRIPTION
**Pull request by Glutexo**
~~⚠️ WARNING: This change could lead to a leak of sensitive data. Do not merge until its safety is confirmed.~~ Update: Although this change may in theory be insecure, there are no real examples of such a leek. See my comment below.

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

The yum.log file only logs messages on actual package installation, not connection or other repository information. As such, it cannot contain sensitive information including IP addresses. Thus, it’s safe to exclude it from IP address obfuscation, causing SOSCleaner not to treat long version numbers as IP addresses. Packages with long versions will no longer trigger false rule hits in the Platform.

Fixes [ESSNTL-4697](https://issues.redhat.com/browse/ESSNTL-4697)

### CODE REVIEW

**Review by xiangce — APPROVED** [review]
Although I don't think the newly added tests could reflect the `excluding` of `yum_log`, I believe that adding it to the `exclude_files` works as expected.

**Comment by Glutexo** [comment]
You are right, @xiangce! The test can be put in a separate pull request, it is not related to the code change. The exact list of excluded specs is not tested, thus there will be no test changes in this pull requests.

**Comment by Glutexo** [comment]
I added a warning to the description and converted the PR to a Draft to make sure it’s not merged before we know for sure the patch does not introduce leakage of sensitive data.

**Comment by xiangce** [comment]
Hi @Glutexo , I marked this PR as `ready` according to the comments of INSGHTCORE-253 and will release it in the next release, Please correct me, If I understand incorrectly. Thanks.

**Comment by Glutexo** [comment]
Created a follow-up https://github.com/RedHatInsights/insights-core/pull/3941.

**Pull request merged**
