### PR TITLE
FileListing class to handle single directory listings for 1.x branch

### PR DESCRIPTION
**Pull request by PaulWay**
Jakub Svoboda identified in issue #827 that the FileListing parser wasn't able to read single directory listings, because a single directory listing doesn't include the directory name in the output and only if the directory name is read will anything else be captured.

This patch fixes that by checking for a path on the command line or in the file path in sosreport format - e.g. 'ls_-la_.etc.pki.tls', with '.' substituted for '/'.  That dotted suffix, converted back to path format, is used as a 'first guess' of the directory.  If a directory heading is found in the output that is used in preference to the first guess.

Tests have been added to check this functionality.

### CODE REVIEW

**Comment by jsvob** [comment]
@PaulWay Hi, I like it. What if we have a spec like `ls -la /etc/yum.repos.d`? The path would get converted to /etc/yum/repos/d IIUC. I would be OK with a solution to that through just documenting that it is a tradeoff and that a consumer of such a `ls` has to be aware of it or has to use `ls -la /dev/null /etc/yum.repos.d`, or having some sort of method that does search and replace in the parsed data to correct it back.

**Comment by PaulWay** [comment]
Hi @jsvob - good point!  Obviously `/etc/yum.repos.d` is captured already in the `LsEtc` parser, but I take your point that a directory listing of a single path that contains dots will be incorrectly back-translated.  In general if you want a directory listed exactly, I think we shouldn't rely on the back-translation - at this stage the best option is to do a recursive listing of the parent.  If you know the directory that you're listing, then you can find that listing in the parser output fairly easily - I don't think we need to concern ourselves with whether its path is exactly as originally given.

In the future I think we should aim to not use `ls` at all and instead have a datasource that captures directory listings in an efficient, safe and unambiguous manner.

**Comment by PaulWay** [comment]
I updated the code to reverse the ' ' to '_' translation (just in case someone's listing a directory with spaces in its name) and with a note in the documentation about the path translations.

I don't know why I'm getting a build error on `sphinx-build -W -b html -qa -E docs docs/_build/html` saying that:
```
Warning, treated as error:
/home/travis/build/RedHatInsights/insights-core/insights/parsers/xfs_info.py:docstring of insights.parsers.xfs_info.XFSInfo.parse_content:3:Unexpected indentation.
```
Because when I run the same command from the command line, I get no error.  Can someone else check this for me?

**Comment by xiangce** [comment]
@PaulWay - I think it's caused by the class XFSInfo missed the docstring entry, then the sphnix works weird. I have fixed it in https://github.com/RedHatInsights/insights-core/pull/941, please take a look at #941. And rebase this PR after #941 is OK and merged.

**Comment by PaulWay** [comment]
Hi @xiangce - thanks for that fix - I've re-submitted this and hopefully it should be good to go now.

**Comment by PaulWay** [comment]
@xiangce Should be all good to go now.

**Comment by jsvob** [comment]
Hi @PaulWay, thanks for documenting that. I agree with your arguments.

Just a note that one might not always want a recursive listing - in cases where the directory might be unpredictably excessively large and only one level of listing is needed anyway.

**Pull request merged**
