### PR TITLE
add spec to collect pmlogsummary of PCP Raw data

### PR DESCRIPTION
**Pull request by xiangce**
- RHINENG-8434
  and mark the pmlogsummary specs as IP/hostname no_obfuscate
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

See RHINENG-8434

### CODE REVIEW

**Comment by upadhyeammit** [comment]
Hello @xiangce thanks for changes, below are my quick thoughts!

I can see the extra text file getting generated, at the same time I think we need to also handle/unsure about below things,

1. When legacy config is there and user puts ros_collect=True in insights-client.conf. In this case I think we should be generating pmlogsummary output using archives of /var/log/pcp/pmlogger/<hostname> path.
2. When legacy config is there and user puts ros_collect=True, however there are no metrics populated at /var/log/pcp/pmlogger/<hostname> path. At the same time legacy path has metrics. Logically in this case we should fail as we don't find metrics at all, however I think with current implementation we will still receive output of pmlogsummary but no archives files?

Let me know your thoughts, at the same time I am still reviewing changes.

**Comment by xiangce** [comment]
Hi @upadhyeammit 
> 1. When legacy config is there and user puts ros_collect=True in insights-client.conf. In this case I think we should be generating pmlogsummary output using archives of /var/log/pcp/pmlogger/ path.

In the current implementation, both sets of information are collected in this scenario (`legacy config is there and user puts ros_collect=True`), I need your input on whether we should:
- stop collecting the old `pmlogsummary` command that is based on `/var/log/pcp/pmlogger/ros/{YESTERDATY}.*`
- and collect the new `pmlogsummary` that is based on `/var/log/pcp/pmlogger/{HOSTNAME}/{YESTERDAY}.*`

> 2. When legacy config is there and user puts ros_collect=True, however there are no metrics populated at /var/log/pcp/pmlogger/ path. At the same time legacy path has metrics. Logically in this case we should fail as we don't find metrics at all, however I think with current implementation we will still receive output of pmlogsummary but no archives files?

I cannot understand `At the same time legacy path has metrics. Logically in this case we should fail as we don't find metrics at all`. it makes me confused.

**Comment by upadhyeammit** [comment]
I was incorrect! There are two different files,
~~~
# cat pmlogsummary_.var.log.pcp.pmlogger.ros.20240401.index_disk.dev.total_hinv.ncpu_kernel.all.cpu.idle_kernel.all.pressure.cpu.some.avg_kernel.all.pressure.io.full.avg_kernel.all.pressure.io.some.avg_kernel.all.pressure.memory.full.avg_kernel.all.pressure.mem 
disk.dev.total ["vda"] 1.245 count / sec
hinv.ncpu  2.000 none
kernel.all.cpu.idle  1.984 none
mem.physmem  4638616.000 Kbyte
mem.util.available  3493705.629 Kbyte

# cat pmlogsummary_.var.log.pcp.pmlogger.aupadhye-rhel9.example.com.20240401.index_disk.dev.total_hinv.ncpu_kernel.all.cpu.idle_kernel.all.pressure.cpu.some.avg_kernel.all.pressure.io.full.avg_kernel.all.pressure.io.some.avg_kernel.all.pressure.memory.full.avg_ 
disk.dev.total ["vda"] 1.245 count / sec
hinv.ncpu  2.000 none
kernel.all.cpu.idle  1.984 none
mem.physmem  4638616.000 Kbyte
mem.util.available  3493705.629 Kbyte
~~~

I was not knowing use of meta dir which actually helped to understand problem with archives because of which legacy collection was failing,
~~~
# /usr/bin/pmlogsummary /var/log/pcp/pmlogger/ros/20240401.index disk.dev.total hinv.ncpu kernel.all.cpu.idle kernel.all.pressure.cpu.some.avg kernel.all.pressure.io.full.avg kernel.all.pressure.io.some.avg kernel.all.pressure.memory.full.avg kernel.all.pressure.memory.some.avg mem.physmem mem.util.available
pmlogsummary: Cannot open archive "/var/log/pcp/pmlogger/ros/20240401.index": Corrupted record in a PCP archive log
~~~

Considering this I can conclude,
1. There are two different files for new and legacy collector, in this way there is no overwriting situation.
2. When both are enabled and system supports both there is no harm to collect both
3. We need to make changes in plugins to accept metrics from new file and spec

So yeah changes looks good to me!

**Review by upadhyeammit — APPROVED** [review]

**Review by JoySnow — APPROVED** [review]
The changes LGTM.

**Comment by xiangce** [comment]
@upadhyeammit @JoySnow - from @upadhyeammit 's comment, I noticed that the `hostname` will be included in the filename of the new `pmlog_summary_new` spec. And all `file name/path` are not candidates for the `obfuscation`, that is, when the customer enabled the `obfuscate_hostname=True`, this spec will keep the `hostname` incorrectly. Based on this, I will use the newly introduced `save_as` feature to rename the file of the `pmlog_summary_new` spec to "pmlog_summary_new". For example, it will look like:
```
# ls insights-archive-xxx/data/insights_commands/pmlog*
insights-archive-xxx/data/insights_commands/pmlog_summary_new
insights-archive-xxx/data/insights_commands/pmlogsummary_.var.log.pcp.pmlogger.ros.20240401.index_disk.dev.total_hinv.ncpu_kernel.all.cpu.idle_kernel.all.pressure.cpu.some.avg_kernel.all.pressure.io.full.avg_kernel.all.pressure.io.some.avg_kernel.all.pressure.memory.full.avg_kernel.all.pressure.mem
```

and as you now know, the `filename` will not cause any conflict or missing-matching, the JSON file under the `meta_data` will record the `relative_path` and help the insights-core to find the right text file.

@upadhyeammit let me know about this change (not committed yet)

**Comment by upadhyeammit** [comment]
> @upadhyeammit @JoySnow - from @upadhyeammit 's comment, I noticed that the `hostname` will be included in the filename of the new `pmlog_summary_new` spec. And all `file name/path` are not candidates for the `obfuscation`, that is, when the customer enabled the `obfuscate_hostname=True`, this spec will keep the `hostname` incorrectly. Based on this, I will use the newly introduced `save_as` feature to rename the file of the `pmlog_summary_new` spec to "pmlog_summary_new". For example, it will look like:
> 
> ```
> # ls insights-archive-xxx/data/insights_commands/pmlog*
> insights-archive-xxx/data/insights_commands/pmlog_summary_new
> insights-archive-xxx/data/insights_commands/pmlogsummary_.var.log.pcp.pmlogger.ros.20240401.index_disk.dev.total_hinv.ncpu_kernel.all.cpu.idle_kernel.all.pressure.cpu.some.avg_kernel.all.pressure.io.full.avg_kernel.all.pressure.io.some.avg_kernel.all.pressure.memory.full.avg_kernel.all.pressure.mem
> ```
> 
> and as you now know, the `filename` will not cause any conflict or missing-matching, the JSON file under the `meta_data` will record the `relative_path` and help the insights-core to find the right text file.
> 
> @upadhyeammit let me know your thoughts about this change (not committed yet)

As we have flexibility to choose the filename, maybe something like `pmlog_summary_based_on_pcp_zeroconf_archives` I suggest, or anything similar to this.

**Comment by xiangce** [comment]
> As we have flexibility to choose the filename, maybe something like `pmlog_summary_based_on_pcp_zeroconf_archives ` I suggest, or anything similar to this.

Sure thing, just renamed it as `pmlogsummary_based_on_pcp_zeroconf_archives`, see the new commit

**Review by JoySnow — APPROVED** [review]

**Comment by xiangce** [comment]
@JoySnow - Thanks for the reminder. I added a parser for the new spec. Please have a look again.

**Review by JoySnow — APPROVED** [review]
It LGTM, thanks @xiangce.

**Review by upadhyeammit — APPROVED** [review]
Thanks for the changes!

**Pull request merged**
