### PR TITLE
httpd conf combiner new test

### PR DESCRIPTION
**Pull request by jsvob**
https://bugzilla.redhat.com/show_bug.cgi?id=1578837

### CODE REVIEW

**Comment by jsvob** [comment]
For the time being, this is heavy work in progress and experimentation with the right approach.

**Comment by jsvob** [comment]
In the end, I found out that the current parser and combiner are adequate for all our current rules.

Relevant findings are in https://bugzilla.redhat.com/show_bug.cgi?id=1578837#c22 (internal to Red Hat).

In this MR, I'm just adding one test with behavior that bewildered me, until I saw it in the form of the test before my eyes; so I'm assuming it might help me or others in the future, while using the httpd_conf combiner.

**Comment by xiangce** [comment]
Hey, @jsvob - The PR looks good to me, I have merged it. But I would like to remind your, in normal, the master branch is the main battlefield, we'd better work on the master and submit PRs against master instead of the 3.0 branch. The PRs merged to the master will be cherry-picked to the 3.0 branch immediately. Thanks.

**Comment by jsvob** [comment]
@xiangce Hi, oh sorry. I see you cherry-picked it to the master - thank you! I'll remember to work with master in the future.

**Pull request merged**
