### PR TITLE
Remove prefix "!" or "*" for yum repolist

### PR DESCRIPTION
**Pull request by huali027**
I found this parser is used in a lot of plugins, and many of them don't consider that maybe
it starts with exclamation mark. I think it is useless for comparation, so we can remove
it in the parser.

### CODE REVIEW

**Comment by huali027** [comment]
@bfahr, if we remove the mark before repo id in the parser, then we don't need to update lots of plugins, what's your opinion for this PR? Please help to review it when you have time, thanks.

**Comment by bfahr** [comment]
@huali027 would you please open an issue for this enhancement.  Is there any specific meaning associated with the `!` and `*` chars?

**Comment by bfahr** [comment]
Based on [this solution](https://access.redhat.com/solutions/2267871), the `!` indicates "the repository has expired metadata".  And based on [this solution](https://access.redhat.com/solutions/59244), the `*` indicates "the first column will start with a '*' if the repo. has metalink data and the latest metadata is not local".  So based on the fact that those chars provide information that could be useful we should not just throw those away, unless there is another column that provides the same information.

**Comment by huali027** [comment]
@bfahr, yes, from the yum man page, we can see the description too. Yesterday I checked all the user cases, generally, we just check if some repo like "rhel-server-rhscl-7-rpms" is enabled with this parser. So in most cases, only the first part of "!rhel-server-rhscl-7-rpms/7Server/x86_64" without a mark is useful. What about we update the key to the first part and keep all the info in the values part? Let me update my patch, you can help to review it to see if it is okay, thanks.

**Pull request merged**
