### PR TITLE
Limits_conf combiner for 1.x branch

### PR DESCRIPTION
**Pull request by PaulWay**
Let's try that again, shall we?  Requesting a merge of the work on https://github.com/RedHatInsights/insights-core/pull/70 for https://github.com/RedHatInsights/insights-core/issues/85

### CODE REVIEW

**Comment by bfahr** [comment]
@PaulWay this PR appears to break the rule `nproc_common_entries`, would you mind to check it?

**Comment by PaulWay** [comment]
@bfahr That's because nproc_common_entries used a different set of parsers (in nproc.py) but the same specs as limits_conf.py.

The solution to this is to fix nproc_common_entries so that it uses the limits_conf parsers, and so that it can cope with these changes.  I've submitted a MR for that in https://github.com/RedHatInsights/insights-plugins/pull/86 .  Once that's done we can apply this, then look at removing the nproc parser.

**Comment by xiangce** [comment]
https://github.com/RedHatInsights/insights-plugins/pull/86 is not merged, trying to push #86  forward.

**Comment by xiangce** [comment]
@PaulWay - This PR will cause insights-plugins broken, so we have to wait for your corresponding PR to plugins being merged.

**Pull request merged**
