### PR TITLE
Supporting python 2.6+ and 3.3+

### PR DESCRIPTION
**Pull request by jhjaggars**

### CODE REVIEW

**Comment by SteveHNH** [comment]
rerun tests

**Comment by SteveHNH** [comment]
rerun tests

**Comment by SteveHNH** [comment]
rerun tests

**Comment by kylape** [comment]
test this please

**Comment by SteveHNH** [comment]
rerun tests

**Comment by kylape** [comment]
test this please

**Comment by kylape** [comment]
test this please

**Comment by SteveHNH** [comment]
rerun tests

**Comment by SteveHNH** [comment]
We have a python3.6 testing container in jenkins now. You can pull in our Jenkinsfile from master and uncomment the python3 stuff at the bottom in order to get that tested with the Jenkins framework. That should cause this PR to get tested with that, but not force everything else to go through python 3.6 testing until this gets merged. :+1:

**Pull request merged**
