### PR TITLE
remove --docker-image-name and a lot of container cruft

### PR DESCRIPTION
**Pull request by gravitypriest**

### CODE REVIEW

**Comment by kylape** [comment]
flake8:

```
./insights/client/containers.py:14:1: F401 'sys' imported but unused
```

**Comment by gravitypriest** [comment]
Thought I took that one out... Must have accidentally removed it in the
build folder instead

**Comment by kylape** [comment]
Not sure why Travis failed.  I'm gonna ignore it.

@brantleyr if you're okay with the changes now, I'll merge.

**Comment by brantleyr** [comment]
@kylape :+1:

**Pull request merged**
