### PR TITLE
Change unordered_compare to deep_compare

### LINKED ISSUE #1494: [python3] `unordered_compare` does support comparing list with dictionaries
In python3 virtualenv, below comparsion is failed:
~~~
result = [{'nearfull_percent': '87%', 'osd_name': 'osd.1'}, {'nearfull_percent': '86%', 'osd_name': 'osd.2'}]
expected = [{'nearfull_percent': '87%', 'osd_name': 'osd.1'}, {'nearfull_percent': '86%', 'osd_name': 'osd.2'}]

    def unordered_compare(result, expected):
        """
        Deep compare rule reducer results when testing.  Developed to find
        arbitrarily nested lists and remove differences based on ordering.
        """
        logger.debug("--Comparing-- (%s) %s to (%s) %s", type(result), result, type(expected), expected)

        if isinstance(result, dict) and expected is None:
            assert result["type"] == "skip", result
            return

        if not all(isinstance(o, six.string_types) for o in (result, expected)):
            assert issubclass(type(result), type(expected))

        if isinstance(result, list):
            assert len(result) == len(expected)
>           for left_item, right_item in six.moves.zip(sorted(result), sorted(expected)):
E           TypeError: '<' not supported between instances of 'dict' and 'dict'
~~~

### PR DESCRIPTION
**Pull request by xiangce**
Resolve #1494

### CODE REVIEW

**Comment by esakaiev** [comment]
test this please

**Comment by bfahr** [comment]
@xiangce the changes look good, but they also break some things, possibly uncovering bugs.

@skontar @matysek you may want to test your code with this PR.  It affects tests with results containing lists.  Currently the unordered_compare does not preserve the list order when comparing results.  This change fixes that and in doing so breaks some tests.

**Comment by matysek** [comment]
@bfahr I tested our code with this PR and it breaks 4 our rules. I will work on fixing it and report back.

**Comment by matysek** [comment]
@bfahr @xiangce I fixed our tests to work with these changes. Should be safe to merge it. Thanks for pinging us.

**Comment by xiangce** [comment]
@matysek - It's merged. Thanks for the response.

**Pull request merged**
