### PR TITLE
change --support behavior, save all logs to a tar

### PR DESCRIPTION
**Pull request by gravitypriest**

### CODE REVIEW

**Comment by kylape** [comment]
This resolves https://github.com/RedHatInsights/insights-core/issues/904

**Comment by gravitypriest** [comment]
Found a bug with the registration check change, closing until I fix it.

**Comment by kylape** [comment]
A few questions:

- Is there a reason the `systemctl` commands can't be combined with the other set of command being executed in `_support_diag_dump`?
- Should we try not to execute the `systemtl` commands on RHEL 6?  It would obviously take more code to detect, but it would clean up the support output a bit.
- Is there really much value of creating a tar of the logs?  It seems trivial for a user to tar up the logs in `/var/log/insights-client`, but on the other hand I guess it doesn't hurt to do it for them.

**Comment by gravitypriest** [comment]
- Good catch, I went through a few iterations when I was refactoring and moving them to the rest of the cmds seems to make sense.
- If the concern is log output I'll just remove the exception log dump when it fails to run.
- My thinking was, this one file could end up being the the only thing they would need to upload when doing a support case.

**Comment by kylape** [comment]
I think it's no big deal to just run systemctl and print that it can't be found on rhel 6.

Eh, sosreport does the same thing as what you're doing here, so let's just leave it.

We can merge once the build passes.

**Comment by kylape** [comment]
```
./insights/client/support.py:13:1: F401 'utilities.run_command_get_output' imported but unused
./insights/client/support.py:139:31: F841 local variable 'o' is assigned to but never used
./insights/client/support.py:142:72: F821 undefined name 'e'
```

**Pull request merged**
