### PR TITLE
feat: add additional messaging for 401 response

### PR DESCRIPTION
**Pull request by gravitypriest**
When a 401 occurs, tell the user that RHSM or basic auth may be incorrect. Additionally, trigger the `handle_fail_rcs` function on the registration check request, which is the first authenticated HTTP call made during the runtime.

### CODE REVIEW

**Review by subpop — APPROVED** [review]

**Comment by patchkez** [comment]
test this please 2

**Comment by patchkez** [comment]
test this please 2

**Comment by patchkez** [comment]
test this please 2

**Comment by patchkez** [comment]
test this please 2

**Comment by patchkez** [comment]
test this please 2

**Comment by patchkez** [comment]
test this please 2

**Comment by patchkez** [comment]
test this please 2

**Comment by patchkez** [comment]
test this please 2

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
run tests

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
test me - new pipeline

**Comment by patchkez** [comment]
test me - new pipeline

**Pull request merged**
