### PR TITLE
feat: Remove --force-reregister command

### PR DESCRIPTION
**Pull request by Glutexo**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Complete Description of Additions/Changes:

* Card ID [CCT-404](https://issues.redhat.com/browse/CCT-404)

The command has been removed from the CLI and from the documentation. It only used to raise a deprecation error message, that being its only presence in the actual logic. There was only a single test verifying the deprecation message.

### CODE REVIEW

**Comment by Glutexo** [comment]
For some reason, GitHub doesn’t allow me to pick neither @m-horky and @DuckBoss as a reviewer.

**Comment by m-horky** [comment]
The commit is missing a Jira reference. Otherwise LGTM.

**Comment by Glutexo** [comment]
Added the JIRA [ticket](https://issues.redhat.com/browse/CCT-404) reference to the description. Updated the branch on the current _master_.

**Comment by m-horky** [comment]
Hi, @Glutexo, the commit still doesn't include the ticket ID, only PR does. We need it in the git history.

**Comment by m-horky** [comment]
Every commit containing change relevant to the card should have the Jira reference. Easy :)

**Comment by Glutexo** [comment]
Added the card reference to the commit message, inspired by other commits already merged in to _master._

**Review by m-horky — APPROVED** [review]
LGTM

**Comment by m-horky** [comment]
@xiangce Hi, ready to merge :)

**Review by chenlizhong — APPROVED** [review]

**Pull request merged**
