### PR TITLE
Ultralight checkins

### PR DESCRIPTION
**Pull request by Glutexo**
Add support for the hourly ultra-light check-ins. Adds a new `--checkin` parameter that sends a PUT request with the system’s Canonical Facts to the Inventory. If Canonical Facts can’t be collected, tries that with Insights ID.

[RHCLOUD-8480](https://issues.redhat.com/browse/RHCLOUD-8480)

### CODE REVIEW

**Comment by Glutexo** [comment]
Ready for review. Asking @subpop, @gravitypriest.

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
All checks have passed ✅

**Review by gravitypriest — APPROVED** [review]

**Comment by Glutexo** [comment]
Awsm! Merge?

**Comment by Glutexo** [comment]
Followed up by https://github.com/RedHatInsights/insights-core/pull/2813 once https://github.com/RedHatInsights/insights-host-inventory/pull/735 is merged.

**Comment by Glutexo** [comment]
https://github.com/RedHatInsights/insights-host-inventory/pull/735 got merged. Adding changes from #2813. This fixes the status code, but not the request format.

**Comment by Glutexo** [comment]
Fixed the request shape. The Canonical Facts are now first-class citizens of the request object. I however need to write some more tests.

**Comment by Glutexo** [comment]
[_get_canonical_facts_](https://github.com/Glutexo/insights-core/blob/b32a6e1a608e1bbe557e5f7e7cd7bb4392f6f1e1/insights/util/canonical_facts.py#L111) does not return a plain _dict_, but a [_Response_](https://github.com/Glutexo/insights-core/blob/b32a6e1a608e1bbe557e5f7e7cd7bb4392f6f1e1/insights/core/plugins.py#L372) object instead. Because there was a bug in this object stringification method, the verbose mode was failing. I fixed the bug in [one](https://github.com/RedHatInsights/insights-core/pull/2807/commits/84aa830390de42ed6cc45284464605d31d07c780) of my previous commits.

Now I improved the tests so they too are using this _Response_ object instead of plain dicts. That means that with the stringification bug in place, they fail together with the executive code. I also added a plugins [test](https://github.com/Glutexo/insights-core/blob/b32a6e1a608e1bbe557e5f7e7cd7bb4392f6f1e1/insights/tests/core/test_plugins.py#L67) targetting this specific bug.

This is now ready for a new review. @gravitypriest, @subpop

**Review by gravitypriest — APPROVED** [review]

**Comment by Glutexo** [comment]
I fixed the pipeline warnings. This can be now merged. @gravitypriest @subpop

**Comment by gravitypriest** [comment]
test this please

**Comment by gravitypriest** [comment]
test this please

**Comment by Glutexo** [comment]
Awesome!

**Pull request merged**
