### PR TITLE
RHCLOUD-9230 Delete pid files on exit

### PR DESCRIPTION
**Pull request by Glutexo**
This is a fix for [RHCLOUD-9230](https://issues.redhat.com/browse/RHCLOUD-9230).

The reported bug was that the _insights-client_ does not delete its (P)PID files if called with the _--version_ argument. The problem is that the files are created whenever the wrapper is used, but deleted only at the end of the _collect and output_ phase. If this phase does not happen, the files are not deleted.

Fixed by registering the delete at the same place where the files are written. Like this, the files are deleted even on failure and regardless of what phases are run or whether even any phase is run. This includes the _--version_ switch that results in no phases being run at all.

Along with this I slipped in these following tiny changes:

- Fixed the tests that got broken by https://github.com/RedHatInsights/insights-core/pull/2675.
- Renamed the _InsightsClient.\_\_init\_\__ _setup_logging_ argument to _from_phase_. I checked both the _insights-core_ and _insights-client_ commit history and the argument is nowhere used by name, the rename should be thus safe.

The tests I added verify only the delete function registration, not the actual delete. The original tests did the same for the writes.

### CODE REVIEW

**Comment by Glutexo** [comment]
Going to fix tests that got borked by #2675.

**Comment by Glutexo** [comment]
Ready for review, @SteveHNH, @gravitypriest, @subpop.

**Comment by Glutexo** [comment]
Ready for review, @SteveHNH, @gravitypriest, @subpop.

**Review by gravitypriest — APPROVED** [review]

**Comment by Glutexo** [comment]
Rebased and resolved conflicts.

**Comment by Glutexo** [comment]
Jenkins failed on

```
fatal: [{{IP_ADDRESS}}]: FAILED! => {"msg": "The field 'remote_user' has an invalid value, which includes an undefined variable. The error was: 'SSH_USER' is undefined"}
```

That should not be problem of this pull request.

**Comment by gravitypriest** [comment]
test this please

**Comment by Glutexo** [comment]
All checks passed!

**Comment by gravitypriest** [comment]
test this please

**Comment by gravitypriest** [comment]
Jenkins tests are timing out. If it's not working by EOD I'll just merge.

**Comment by gravitypriest** [comment]
test this please

**Comment by Glutexo** [comment]
It was once green, but not before the merge.

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
Checks are green once again. @gravitypriest please merge before it fails again. 😃

**Pull request merged**
