### PR TITLE
Make /tmp/insights-client-egg-release manipulation more secure

### PR DESCRIPTION
**Pull request by Glutexo**
Catch errors that can be caused by malicious tampering with _/tmp/insights-client-egg-release_. If _/tmp_ doesn’t have the Sticky Bit set, any user can create this entry and link it to a too big or even infinite (like _/dev/zero_) file causing an _OSError_ (No space left on device) on write or _MemoryError_ on read.

This is a first step to alleviate [RHCLOUD-12066](https://issues.redhat.com/browse/RHCLOUD-12066)/[BZ 1920344](https://bugzilla.redhat.com/show_bug.cgi?id=1920344). The next step is going to be using a dedicated directory that would not be world writable.

### How to reproduce:

1. Unset sticky bit from _/tmp_. This makes user created files accessible for _root_.

#### MemoryError on read

1. Symlink /dev/zero to _/tmp/insights-client-egg-release_.
2. Run _insights-client_ with _auto_update=False_ and _--verbose_.
3. See that the egg release file read fails with “Could not read the egg release file” instead of crashing.
4. See that the collection succeeds.

#### OSError on write

1. Make _/var/tmp_ very small, e.g. by
   ```
   $ fallocate -l 10M small_tmp
   $ mkfs.ext4 -j small_tmp
   $ sudo mount small_tmp /var/tmp
   ```
2. Make _/tmp/insights-client-egg-release_ too big for the tmp.
   ```
   $ fallocate -l 20M /tmp/insights-client-egg-release
   ```
3. Run _insights-client_ with _auto_update=False_, _--verbose_ and _--no-upload_.
4. See that the egg release file write fails with “Could not add the egg release file to the archive” instead of crashing.
5. See that the collection succeeds.
6. See that the saved collection file contains an empty _/egg_release_ file.

### CODE REVIEW

**Comment by Glutexo** [comment]
Asking @gravitypriest and @subpop for a review.

**Review by subpop — APPROVED** [review]
LGTM

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
Unit tests passed. continuous-integration/jenkins/pr-merge has been ok once already, but it started failing for reasons unrelated to the pull request.

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by Glutexo** [comment]
Yay yay!!

**Pull request merged**
