### PR TITLE
handle 413 status, raise error if received

### PR DESCRIPTION
**Pull request by gravitypriest**

### CODE REVIEW

**Comment by patchkez** [comment]
Jenkins job failed for test TestOptions.test_upload_too_large, we need to amend the test case to handle different stdout message. 
screenshot-20191121@124951

**Comment by patchkez** [comment]
test this please

**Comment by gravitypriest** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by gravitypriest** [comment]
test this please

**Comment by gravitypriest** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by gravitypriest** [comment]
test this please

**Comment by gravitypriest** [comment]
Test failures are API side, merging.

**Pull request merged**
