### PR TITLE
Only collect "*.conf" for nginx

### PR DESCRIPTION
**Pull request by huali027**
Signed-off-by: Huanhuan Li <huali@redhat.com>

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### CODE REVIEW

**Comment by huali027** [comment]
@xiangce, generally, only "*.conf" are the configuration files. I found if some unused files have a syntax error, as a result, the archive won't be hit due to the exceptions. So I added the "*.conf" suffix. Please help to review, thanks.

**Comment by xiangce** [comment]
@huali027 - This change also requires an update to the `uploader.json` file.

**Comment by huali027** [comment]
@xiangce, sure, thanks for the reminder, I'll submit an MR for uploader.json.

**Review by xiangce — APPROVED** [review]
Approved pending the approval of the SPEC Change.

**Pull request merged**
