### PR TITLE
feat: enhance GrubbyDefaultKernel to skip warn msgs

### PR DESCRIPTION
**Pull request by JoySnow**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Complete Description of Additions/Changes:

Resolve https://github.com/RedHatInsights/insights-core/issues/3759 

Tested with RAT#737, only has "Invalid output: no kernel line: {0}" type errors after the change, and the `parser_error` was largely reduced.

### CODE REVIEW

**Comment by JoySnow** [comment]
Hi @xiangce , could you help review the changes here?

**Comment by JoySnow** [comment]
test me

**Review by xiangce — APPROVED** [review]

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
test me

**Pull request merged**
