### PR TITLE
use determine_hostname func to get fqdn

### PR DESCRIPTION
**Pull request by gravitypriest**

### CODE REVIEW

**Comment by gravitypriest** [comment]
TODO: factor this code out of insights/client/utilities.py

**Comment by bfahr** [comment]
@gravitypriest this change appears to break the command line tools:
```
[insights-core] devbox:~/insights/insights-core (master) 
$ insights cat hostname
CommandOutputProvider("'/bin/hostname -f'")
devbox
[insights-core] devbox:~/insights/insights-core (master) 
$ insights cat insights.specs.default.DefaultSpecs.hostname
CommandOutputProvider("'/bin/hostname -f'")
devbox
[insights-core] devbox:~/insights/insights-core (master) 
$ git checkout -b determine-hostname-spec origin/determine-hostname-spec
Branch determine-hostname-spec set up to track remote branch determine-hostname-spec from origin.
Switched to a new branch 'determine-hostname-spec'
[insights-core] devbox:~/insights/insights-core (determine-hostname-spec) 
$ insights cat hostname
Missing Dependencies:
    At Least One Of:
        insights.specs.insights_archive.InsightsArchiveSpecs.hostname
        insights.specs.sos_archive.SosSpecs.hostname
[insights-core] devbox:~/insights/insights-core (determine-hostname-spec) 
$ insights cat insights.specs.default.DefaultSpecs.hostname
object of type 'NoneType' has no len()
```

**Comment by bfahr** [comment]
@gravitypriest should this be closed given that #2587 has been merged?

**Comment by gravitypriest** [comment]
@bfahr That one's for a slightly different use case -- needed a quick turnaround for compliance because the hostname spec wasn't working for them on RHEL 6. I think we want to keep pursuing this one as well; I'll revisit next sprint.

**Pull request closed without merging**
