### PR TITLE
XFS info improvements

### PR DESCRIPTION
**Pull request by PaulWay**
* Write documentation.
* Extract mount point from file name if possible.
* Store device name in attribute as well.
* Throw errors if the mapper didn't find expected things in the info, like a 'meta-data' and 'data' sections.
* Less verbose ``__repr__`` method
* Test all of the above.  100% code coverage in tests.

### CODE REVIEW

**Comment by bfahr** [comment]
@PaulWay there's a problem accessing this pull request, it may be a problem accessing it from your fork. Maybe its related to the project going public today and your fork possibly having different permissions?

**Comment by bfahr** [comment]
Making your fork public may fix the problem.

**Comment by PaulWay** [comment]
Hi @bfahr - yes, it was still private.  I've made it public :-)

**Comment by PaulWay** [comment]
Not sure why that final commit (to fix the path in the docs rst) hasn't come to here.

**Comment by PaulWay** [comment]
Moving this over to https://github.com/RedHatInsights/insights-core/pull/19 since that does seem to be working.

**Pull request closed without merging**
