### PR TITLE
feat: Parser for "ls systemd units"

### PR DESCRIPTION
**Pull request by jobselko**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

This PR aims to consolidate all `"ls systemd units"` parsers into one file. The combiner will be created afterwards.

MR with relevant changes in insights-core-assets: !437

### CODE REVIEW

**Comment by xiangce** [comment]
@jobselko - Would you please merge all these `ls systems units` specs into one? just the `ls_etc`: https://github.com/RedHatInsights/insights-core/blob/bbc2186e17d039e0f6a3e4a8d3eabcfaec4670f7/insights/specs/default.py#L322-L325


In this way, all the `ls` results will be wrapped into one `simple_file` and the combiner you mentioned may be not required.

**Comment by psachin** [comment]
Hey @jobselko I think we should [deprecate](https://insights-core.readthedocs.io/en/latest/api.html?highlight=deprecate#feature-deprecation) the parsers instead of deleting them directly since this is a public repo we don't know whether the parser is already in use. A deprecating warning will alert the user against the alternative parser or the new module where it is migrated (in this case)

**Comment by jobselko** [comment]
@xiangce I reworked it. Thank you!
@psachin I do not think this would be a problem. These parsers are unused (by our teams) and were added around three months ago.

**Review by xiangce — APPROVED** [review]
@jobselko it looks good to me

**Comment by jobselko** [comment]
I came across these bugs: #3453, #3454

**Review by psachin — APPROVED** [review]

**Comment by xiangce** [comment]
@jobselko - You missed updating the `insights_archive.py` file in this PR

**Review by xiangce — APPROVED** [review]

**Comment by xiangce** [comment]
The `python26-test` in CI failed due to an environmental issue. 
~~~
Certificate did not match expected hostname: pypi.python.org.
~~~
I'll ignore it and merge this PR

**Pull request merged**
