### PR TITLE
fix: update ubuntu image for 2.6 test

### PR DESCRIPTION
**Pull request by tiran**
### All Pull Requests:

Check all that apply:

* [X] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [X] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

Based on PR https://github.com/RedHatInsights/insights-core/pull/3734

Signed-off-by: Christian Heimes <cheimes@redhat.com>
Signed-off-by: ahitacat <ahitacat@redhat.com>
Co-authored-by: ahitacat <ahitacat@redhat.com>

### CODE REVIEW

**Comment by xiangce** [comment]
@tiran Hi, This looks nice. Thanks for troubleshooting. May I know if this PR is ready? and would you please fix the `DCO` as per the steps [here](https://github.com/RedHatInsights/insights-core/pull/3766/checks?check_run_id=13016841301)?

**Comment by tiran** [comment]
@xiangce Please take a look. I have addressed the DCO issue and gave credit to ahitaca.

**Review by xiangce — APPROVED** [review]
It looks good to me

**Comment by xiangce** [comment]
@ahitacat - Would you please review too? I think you are also interested in it.

**Review by ahitacat — APPROVED** [review]
Oh! Thanks @tiran to continue the starting work :tada: 
This looks good

**Pull request merged**
