### PR TITLE
Remove "is_satellite_server" and "is_satellite_capsule"

### PR DESCRIPTION
**Pull request by huali027**
* Since the combiner "SatelliteVersion" and "CapsuleVersion" is already raises
  SkipComponent if it is not satellite server or capsule, so use it directly

Signed-off-by: Huanhuan Li <huali@redhat.com>

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Complete Description of Additions/Changes:

I want to separate datasource ""is_satellite_server" and "is_satellite_capsule", but I found the combiner "SatelliteVersion" and "CapsuleVersion" already raise SkipComponent if it is not satellite server or capsule, so use it directly.

### CODE REVIEW

**Comment by huali027** [comment]
@xiangce, please help to review

**Review by xiangce — APPROVED** [review]
Looks good to me

**Comment by vdymna** [comment]
This looks good to me.

**Comment by xiangce** [comment]
Related to #3087

**Pull request merged**
