### PR TITLE
Fix a bug that it can not parse output when there is no yum name

### PR DESCRIPTION
**Pull request by huali027**
* On production, some of the outputs have no column of "yum name"
- fix: #2149 

Signed-off-by: Huanhuan Li <huali@redhat.com>

### CODE REVIEW

**Comment by bfahr** [comment]
@huali027 is there an open Issue for this problem?  If not could you please create one.

**Comment by xiangce** [comment]
Issue #2149 is opened

**Comment by huali027** [comment]
@xiangce, looks good to me, it's much better than hard code something, thanks.

**Comment by huali027** [comment]
@bfahr, please help to review this PR when you have time as soon as possible since this is a bug of the parser, customers will see wrong info due to this issue.

**Comment by xiangce** [comment]
@bfahr @huali027 - the test cases of some rules need to update according to this patch at first, I'm working on it. will let you when everything is ready.

**Comment by xiangce** [comment]
@bfahr, The test cases are fixed. Since this Patch is for a bug needs to be fixed asap, I going to merge it at first. If you have any supplement, please feel free to open an issue.

**Pull request merged**
