### PR TITLE
Update Verifier code to allow for signature validation

### PR DESCRIPTION
**Pull request by aleccohan**
Update Verifier code to allow for signature validation testing.

### CODE REVIEW

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by aleccohan** [comment]
@patchkez Just tested on a fresh rhel8 machine.

used `./build_client_egg.sh` and `BYPASS_GPG=True EGG=insights.zip insights-client --no-gpg`

and validation was successful

**Comment by patchkez** [comment]
test this please

**Comment by gravitypriest** [comment]
Merging, failure in pipeline is due to ultralight checkin failure unrelated to this PR.

**Pull request merged**
