### PR TITLE
correct error in log file creation

### PR DESCRIPTION
**Pull request by gavin-romig-koch**
The original code was a problem because if you were not running as 'root' you couldn't create '/var/log/insights-client/' which is what constants.log_dir was set to by default.

### CODE REVIEW

**Comment by brantleyr** [comment]
I don't know that this is an issue. You can override the default logging file with --logging-file or pass in custom options when instantiating the API through Python.

**Comment by gavin-romig-koch** [comment]
The existing code will always use, check for and create, the directory defined in constants.log_dir, _not_ the directory specified by --logging-file/configuration file.  Even if you specify --logging-file it will still check for and try to create the directory in constants.log_dir.

The actual log will be written to the right place, using --logging-file/configuration, but the directory check and make are always on the directory in constants.log_dir.

**Comment by brantleyr** [comment]
I believe this has been resolved in the latest logging handlers by @kylape.

**Comment by kylape** [comment]
Hey @gavin-romig-koch just to finish this off -- I did a whole bunch of refactoring that got merged right before you made your changes in this PR.  They definitely make sense, but it would have been a good chunk of work to take your changes and merge them into what I had done.  So I just took the issue you raised and included a fix (very similar to yours) on top of the logging changes I already made.  So you might check out `master` and verify that it works as you expect now.

**Pull request closed without merging**
