### PR TITLE
test: Add more playbooks to verifier's test suite

### PR DESCRIPTION
**Pull request by m-horky**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### CODE REVIEW

**Comment by m-horky** [comment]
This is currently blocked by #4175

**Comment by xiangce** [comment]
@m-horky the #4175 is merged, please let me know if we should also get this PR be released together in this cycle. Thanks.

**Comment by m-horky** [comment]
@xiangce It's not necessary, but it's always nice to keep things together, I'll leave that up to you :)

**Review by xiangce — APPROVED** [review]
looks good to me

**Pull request merged**
