### PR TITLE
Uptime improved processing and test coverage

### PR DESCRIPTION
**Pull request by PaulWay**
Implemented parsing code as regular expressions, since it eliminates a lot of the branch test complexity in the code.

Simplified the tests down to a series of data structures.

All parser and combiner tests pass, all Insights-Plugins tests pass, test coverage is 100% including all branches in both parser and combiner.

### CODE REVIEW

**Comment by PaulWay** [comment]
OK, it looks the build is failing because both the parser and combiner create an object called 'Uptime'.  What's your preference for sorting that out, @bfahr?

**Comment by PaulWay** [comment]
I really don't get how I can do a complete test run and everything passes here and then I push my update here and everything is broken.

**Comment by xiangce** [comment]
@PaulWay - This is because there is a named tuple being named `Uptime`, the building would be OK after renaming it to another name.

**Comment by bfahr** [comment]
@PaulWay if you will edit the docstring in `insights.combiners.uptime.uptime` and for the return time of this function user the full type name `insights.combiner.uptime.Uptime` it will fix the problem with the doc build.  Sphinx can't resolve the type when there is a duplicate name and there is no context provided.

**Comment by bfahr** [comment]
@PaulWay @xiangce once the doc build error is fixed I approve.

**Comment by xiangce** [comment]
@PaulWay, Please re-submit this improvement to 1.x branch after this PR is merged, Thanks

**Pull request merged**
