### PR TITLE
WIP: Enhance mount.py

### PR DESCRIPTION
**Pull request by JoySnow**
Use __slots__ in MountEntry to escape __dict__.
  Add doctest.
Signed-off-by: XiaoXue Wang <xiaoxwan@redhat.com>

### CODE REVIEW

**Comment by bfahr** [comment]
@JoySnow what is the motivation for this change, is there an issue that this addresses?  By essentially adding the code in a shared module, LegacyItemAccess, into this module.

**Comment by xiangce** [comment]
@JoySnow - is this satisfied with by #2070?

**Comment by JoySnow** [comment]
@xiangce 
As we had talked, this PR is not covered by https://github.com/RedHatInsights/insights-core/pull/2070 's current code. They are for different purposes.
You can go ahead of your PR and ignore this one.

**Comment by JoySnow** [comment]
@bfahr  
This PR is meant to use `__slots__` in `MountEntry` object.  To save some memory usage.
And the most important thing here is to remove the usage of  `self.data` to keep the data only in `attributes`.   
I'd like to close this PR for now and see what we can do after the PR https://github.com/RedHatInsights/insights-core/pull/2070 is finished.

**Pull request closed without merging**
