### PR TITLE
exit when no docker-py

### PR DESCRIPTION
**Pull request by brantleyr**

### CODE REVIEW

**Comment by kylape** [comment]
Is there a reason we don't add this as an optional dependency in our RPM spec?  It seems like that would be a more seamless user experience.

**Comment by brantleyr** [comment]
@kylape are you suggesting adding it into the RPM as a weak dependency?

**Comment by brantleyr** [comment]
@kylape even if we do add it in as an optional dependency in the RPM, I think we should still have this failsafe check.

**Comment by kylape** [comment]
Yeah, good point.  Doesn't hurt to have the check.

**Pull request merged**
