### PR TITLE
Fix exception thrown from Scheduler parser

### PR DESCRIPTION
**Pull request by skontar**
* [X] Have you followed the guidelines in our Contributing document?
* [X] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Issue/Bug Fix:
When there is no active scheduler, the parser throws an exception.
This change fixes the problem.

### CODE REVIEW

**Review by jsvob — APPROVED** [review]

**Review by kgrant-rh — APPROVED** [review]

**Comment by bfahr** [comment]
@skontar when you submitted this PR, did you get this [PR template](https://github.com/RedHatInsights/insights-core/blob/master/.github/pull_request_template.md)?

**Comment by skontar** [comment]
@bfahr yes, I did. However, it did not seem very relevant for this fix (there is no issue created for the problem, even when it fixes an "issue", I was unsure if it is an "enhancement", it was not clear if it is a guideline or if I should leave the all the headings or remove them etc.), so I removed it.

**Comment by skontar** [comment]
@bfahr I am fine with including it, but to be honest, I am unsure how it should look like.

**Review by lhuett — APPROVED** [review]
Looks good.

**Pull request merged**
