### PR TITLE
Fix HTTP_PROXY warning condition

### PR DESCRIPTION
**Pull request by Glutexo**
Added a condition that makes the HTTP proxy warning appear only if HTTPS_PROXY is not defined. Also added tests for all possible combinations of the enviroment settings and _InsightsConfig_ constructor arguments.

I only added unit tests verifying the _sys.stdout.write_ calls. It looks like this is how it’s done with no integrations tests that would call the whole Insights Client and reads its output. If I missed such test suite, please let me know and I‘ll add a test like that.

Side note: I believe the warning should be written to _stderr_, not _stdout_. Maybe even use a logger. But that’s not in scope of this pull request.

### CODE REVIEW

**Comment by Glutexo** [comment]
Finally got to this after the winter break. Added tests and ready for review. @subpop @gravitypriest

**Review by subpop — APPROVED** [review]

**Comment by Glutexo** [comment]
There is one failing test _src.tests.client.v3.test_client_options_. I am pretty positive that I didn’t introduce any change that would cause them to fail.

**Comment by Glutexo** [comment]
test this please

**Review by gravitypriest — APPROVED** [review]

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by Glutexo** [comment]
Pavol from the QE [approved](https://issues.redhat.com/browse/RHCLOUD-6621?focusedCommentId=15679662&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15679662). I don’t have permission to merge though. @gravitypriest, @subpop May I ask for a merge?

**Comment by Glutexo** [comment]
(Maybe it’s because there is a failing test?)

**Pull request merged**
