### PR TITLE
Fix net logger

### PR DESCRIPTION
**Pull request by SteveHNH**
Moving the logs regarding connection requests and responses to the net_logger

[RHCLOUD-2198](https://projects.engineering.redhat.com/browse/RHCLOUD-2198)
BZ #1708685

### CODE REVIEW

**Comment by fstavela** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by SteveHNH** [comment]
Closing in favor of using a new log level rather than doing any net_logger updates

**Pull request closed without merging**
