### PR TITLE
feat: new option to show hit result only for insights-run

### PR DESCRIPTION
**Pull request by xiangce**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Complete Description of Additions/Changes:

This is for INSGHTCORE-197
- It added a new option `--no-details` for the `insights-run`, 
   only the FAIL/PASS result will be outputted with this option.
   This option only works for the `text` format.

### CODE REVIEW

**Comment by jholecek-rh** [comment]
@xiangce Thank you for responding to the user feedback so quickly!

I'm thinking if a new built-in formatter, e.g. `-f text_short`, wouldn't be better than a global CLI argument which is applies only to a specific formatter.  I would reserve CLI  arguments for limiting the scope globally (respected automatically by all formatters) and controlling the amount of debugging information (`-D`, `-t`, `-d` switches). WDYT?

**Comment by xiangce** [comment]
> I'm thinking if a new built-in formatter, e.g. `-f text_short`, wouldn't be better than a global CLI argument which is applies only to a specific formatter. I would reserve CLI arguments for limiting the scope globally (respected automatically by all formatters) and controlling the amount of debugging information (`-D`, `-t`, `-d` switches). WDYT?

Nope, I don't think so. the `--no-details` can also be a global option. it can be reused in the future when other formats e.g. JSON and HTML also want such a `summary` output.

**Comment by jholecek-rh** [comment]
@xiangce Right, I misunderstood how the CLI arguments work. There's probably space for improving clarity, but let's save that for another day. :slightly_smiling_face:

**Comment by xiangce** [comment]
test me

**Pull request merged**
