### PR TITLE
Updating sos_archive to parse file for GSS rule

### PR DESCRIPTION
**Pull request by mohitkumarrh**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:
adding systemd_analyze_blame = simple_file("insights_commands/systemd-analyze_blame")  in insights_archive.py

<!--
Provide complete details of the issue or enhancement. You may link to existing open publicly-accessible issues or enhancement requests that provide these details.

Please do not include links to any websites that are not publicly accessible. You may include non-link reference numbers to help you and your team identify non-public references. 

This information is necessary before your PR can be reviewed.

### CODE REVIEW

**Review by xiangce — CHANGES_REQUESTED** [review]
@mohitkumarrh - please fix the DCO check error
- [DCO Details](https://github.com/RedHatInsights/insights-core/pull/3432/checks?check_run_id=6684602034)
And it should be `sos_archives.py` in the description section, Right?

**Comment by psachin** [comment]
> @mohitkumarrh - please fix the DCO check error
> 
>     * [DCO Details](https://github.com/RedHatInsights/insights-core/pull/3432/checks?check_run_id=6684602034)
>       And it should be `sos_archives.py` in the description section, Right?

@xiangce As this is specific to the GSS, we better move this to the internal repo `shared_rules/specs/sos_archive.py`

**Comment by xiangce** [comment]
> > @mohitkumarrh - please fix the DCO check error
> > ```
> > * [DCO Details](https://github.com/RedHatInsights/insights-core/pull/3432/checks?check_run_id=6684602034)
> >   And it should be `sos_archives.py` in the description section, Right?
> > ```
> 
> @xiangce As this is specific to the GSS, we better move this to the internal repo `shared_rules/specs/sos_archive.py`

Nope, the case only occurs when the spec is for GSS rules only.

As this spec was once added for an advisor rule, the parser is already implemented in the core. In this case, it's Okay to enable it for `sos_archvies`.

**Comment by xiangce** [comment]
The CI failed due to environmental issues, I ignored the failed tests and merged this PR directly.

**Pull request merged**
