### PR TITLE
Spec to collect pcp data via pmlogsummary

### PR DESCRIPTION
**Pull request by patilsuraj767**
This spec will collect the pcp data needed for ROS service.

### CODE REVIEW

**Review by bfahr — COMMENTED** [review]
@patilsuraj767 these changes are not necessary.  The logic you have implemented in the spec should be implemented in a rule instead using one of the `Ps` parsers.  You may need to add the filter string `pmlogger` to your rule in order for the particular lines you want to be collected.

**Comment by patilsuraj767** [comment]
@bfahr Can you please check the PR again. I have changed the way to detect if the `pmlogger` service is enabled. Basically, I want `pmlogsummary` command should only be run if `pmlogger` service is enabled.

**Review by CodeHeeler — COMMENTED** [review]
I reviewed this along with @beav earlier today. The code looks good and provides the data you want.

The only potential concern is that the command took 33 seconds to run, so wanted to ask here whether folks felt that is acceptable or whether this adds too much time to the run on the client systems?

**Comment by patilsuraj767** [comment]
@CodeHeeler Are you referring to the main insights-client command? Because pmlogsummary command in the spec should not take that much time. 
In my test system with the minimal configuration, it is taking less than a second. Check the below output. 
```
# time pmlogsummary /var/log/pcp/pmlogger/dhcp200-235.gsslab.pnq.redhat.com/20210210.index mem.util.used mem.physmem kernel.all.cpu.user kernel.all.cpu.sys kernel.all.cpu.nice kernel.all.cpu.steal kernel.all.cpu.idle disk.all.total
mem.util.used  3327953.538 Kbyte
mem.physmem  3997600.000 Kbyte
kernel.all.cpu.user  0.004 none
kernel.all.cpu.sys  0.002 none
kernel.all.cpu.nice  0.002 none
kernel.all.cpu.steal  0.000 none
kernel.all.cpu.idle  3.986 none
disk.all.total  0.224 count / sec

real	0m0.901s
user	0m0.830s
sys	0m0.054s

```

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by beav** [comment]
I did two runs in a row just now on my laptop with ssd drive and got 17 sec and 19 sec. 

```
$ time pmlogsummary /var/log/pcp/pmlogger/zampano/20210209.index mem.util.used mem.physmem kernel.all.cpu.user kernel.all.cpu.sys kernel.all.cpu.nice kernel.all.cpu.steal kernel.all.cpu.idle disk.all.total
mem.util.used  13797602.134 Kbyte
mem.physmem  16257972.000 Kbyte
kernel.all.cpu.user  1.144 none
kernel.all.cpu.sys  0.330 none
kernel.all.cpu.nice  0.001 none
kernel.all.cpu.steal  0.000 none
kernel.all.cpu.idle  6.415 none
disk.all.total  25.862 count / sec

real    0m17.248s
user    0m17.050s
sys     0m0.141s


$ time pmlogsummary /var/log/pcp/pmlogger/zampano/20210209.index mem.util.used mem.physmem kernel.all.cpu.user kernel.all.cpu.sys kernel.all.cpu.nice kernel.all.cpu.steal kernel.all.cpu.idle disk.all.total
mem.util.used  13797602.134 Kbyte
mem.physmem  16257972.000 Kbyte
kernel.all.cpu.user  1.144 none
kernel.all.cpu.sys  0.330 none
kernel.all.cpu.nice  0.001 none
kernel.all.cpu.steal  0.000 none
kernel.all.cpu.idle  6.415 none
disk.all.total  25.862 count / sec

real    0m19.880s
user    0m19.631s
sys     0m0.153s
```

Are your PCP log files similar size to these?

```
$ ll -h /var/log/pcp/pmlogger/zampano/20210209*
-rw-r--r--. 1 pcp pcp 7.4M Feb  9 03:25 /var/log/pcp/pmlogger/zampano/20210209.0.xz
-rw-r--r--. 1 pcp pcp 7.5M Feb  9 06:41 /var/log/pcp/pmlogger/zampano/20210209.1.xz
-rw-r--r--. 1 pcp pcp 9.6M Feb  9 09:44 /var/log/pcp/pmlogger/zampano/20210209.2.xz
-rw-r--r--. 1 pcp pcp 8.1M Feb  9 12:53 /var/log/pcp/pmlogger/zampano/20210209.3.xz
-rw-r--r--. 1 pcp pcp 8.5M Feb  9 15:57 /var/log/pcp/pmlogger/zampano/20210209.4.xz
-rw-r--r--. 1 pcp pcp 8.5M Feb  9 19:02 /var/log/pcp/pmlogger/zampano/20210209.5.xz
-rw-r--r--. 1 pcp pcp  11M Feb  9 22:00 /var/log/pcp/pmlogger/zampano/20210209.6.xz
-rw-r--r--. 1 pcp pcp 6.1M Feb 10 00:10 /var/log/pcp/pmlogger/zampano/20210209.7.xz
-rw-r--r--. 1 pcp pcp  64K Feb 10 00:10 /var/log/pcp/pmlogger/zampano/20210209.index
-rw-r--r--. 1 pcp pcp 344K Feb 10 00:08 /var/log/pcp/pmlogger/zampano/20210209.meta.xz
```

**Comment by patilsuraj767** [comment]
@beav Seems like your data is from the base machine so has a huge amount of logs. 

As I have separate test VM for PCP I guess data/logs are very limited. 
```
# ll -h /var/log/pcp/pmlogger/client.example.com/20210209*
-rw-r--r--. 1 pcp pcp 633K Feb 10 00:10 /var/log/pcp/pmlogger/client.example.com/20210209.0.xz
-rw-r--r--. 1 pcp pcp  12K Feb 10 00:10 /var/log/pcp/pmlogger/client.example.com/20210209.index
-rw-r--r--. 1 pcp pcp  60K Feb 10 00:10 /var/log/pcp/pmlogger/client.example.com/20210209.meta.xz
```

**Comment by patilsuraj767** [comment]
@beav Is your PCP service running in default configuration? OR you have configured it to collect extra metrics/data.

**Comment by beav** [comment]
> @beav Is your PCP service running in default configuration? OR you have configured it to collect extra metrics/data.

It is just regular as far as I can tell

```
$ rpm -V pcp
.......T.  c /etc/pcp/pmcd/pmcd.conf
```

**Comment by beav** [comment]
@patilsuraj767 can you mark this PR as WIP until its ready for re-review? thanks!

**Comment by patilsuraj767** [comment]
@beav I think we can close this PR as @bfahr has opened the new PR - [here](https://github.com/RedHatInsights/insights-core/pull/2950)

**Comment by beav** [comment]
@pgarciaq if you run it on a "quiet" system it runs quickly. However if you run it on a system that was busy for a few hours, it takes a long time. Can you check the size of the pcp directory on your instance?

**Comment by pgarciaq** [comment]
> @pgarciaq if you run it on a "quiet" system it runs quickly. However if you run it on a system that was busy for a few hours, it takes a long time. Can you check the size of the pcp directory on your instance?

4.2 MB and 5.7 MB. They have only been running for 1 week.

**Pull request closed without merging**
