### PR TITLE
Obey -m flag for rules. Use default formatter when no CONTENT available.

### LINKED ISSUE #1479: The human readable rule report includes rules with missing requirements

### LINKED ISSUE #1480: rules without CONTENT produce hard to interpret reports
Rules can provide a jinja2 template in a CONTENT variable on their module to be used when creating human readable rule reports. Rules that don't provide the variable produce output that's hard to read.

### PR DESCRIPTION
**Pull request by csams**
Fixes #1479. Fixes #1480.

### CODE REVIEW

**Comment by bfahr** [comment]
Related to changes in #1465

**Comment by bfahr** [comment]
@csams @wushiqinlou I'd like to come to a consensus on how the output should look for the `-m` switch.  I created a modified `stand_alone` script to help compare the two PR here: https://gist.github.com/bfahr/28b4112d628a9e4215ab3bc07b0cadc5

**Comment by xiangce** [comment]
@bfahr @csams - What we want to re-format is the `Missing Requirements:` part.
Currently, based on this PR, this part looks like:
~~~
(.python2) ❱ insights-run -p telemetry.rules.plugins.sap.sap_compat_issue /tmp/a.tar.gz -m
Install colorama if console colors are preferred.
---------
Progress:
---------
ES
Missing Requirements:
{<insights.core.spec_factory.simple_command object at 0x10bb83c10>: ([<class 'insights.core.context.HostContext'>], []), <class 'insights.parsers.systemid.SystemID'>:
([insights.specs.Specs.systemid], []), <insights.core.spec_factory.simple_file object at 0x10bae4450>: ([<class 'insights.core.context.SosArchiveContext'>], []), <func
tion check_sap_suggested_repo at 0x10bc80410>: ([<class 'insights.combiners.sap.Sap'>], []), <insights.core.spec_factory.simple_command object at 0x10b9e6a10>: ([<clas
s 'insights.core.context.HostContext'>], []), <insights.core.spec_factory.simple_file object at 0x10baf1a90>: ([<class 'insights.core.context.SosArchiveContext'>], [])
, <insights.core.spec_factory.first_of object at 0x10bae44d0>: ([], [[<insights.core.spec_factory.simple_file object at 0x10bae43d0>, <insights.core.spec_factory.simpl
e_file object at 0x10bae4450>]]), <insights.core.spec_factory.simple_command object at 0x10bb689d0>: ([<class 'insights.core.context.HostContext'>], []), <insights.cor
e.spec_factory.simple_command object at 0x10b9d7b10>: ([<class 'insights.core.context.HostContext'>], []), <insights.core.spec_factory.simple_file object at 0x10baf1d1
0>: ([<class 'insights.core.context.SosArchiveContext'>], []), insights.specs.Specs.systemid: ([], [[<insights.core.spec_factory.first_of object at 0x10b9d72d0>]]), <f
unction check_hana_rhel7_e4s_repo at 0x10bc80398>: ([<class 'insights.combiners.sap.Sap'>], []), <insights.core.spec_factory.simple_command object at 0x10baa1e90>: ([<
class 'insights.core.context.HostContext'>], []), <insights.core.spec_factory.simple_command object at 0x10bb3a590>: ([<class 'insights.core.context.HostContext'>], []
), <insights.core.spec_factory.simple_file object at 0x10bae43d0>: ([<class 'insights.core.context.SosArchiveContext'>], []), <insights.core.spec_factory.first_of obje
ct at 0x10b9d72d0>: ([], [[<insights.core.spec_factory.simple_file object at 0x10b9d71d0>, <insights.core.spec_factory.simple_file object at 0x10b9d7250>]])}


-------------
Rule Results:
-------------
telemetry.rules.plugins.sap.sap_compat_issue.report
---------------------------------------------------
Missing requirements
    All: ['insights.combiners.sap.Sap'] Any:
~~~

However, we want to simplify the `Missing Requirements` as below (#1465)
~~~
(.python2) ❱ insights-run -p telemetry.rules.plugins.sap.sap_compat_issue /tmp/a.tar.gz -m                                                                    [30/6685]
Install colorama if console colors are preferred.
---------
Progress:
---------
ES
Requested File Not Collected For Following Specs:
insights.specs.Specs.systemid

File Collected However Content Not Correct For Following Parser:
<class 'insights.combiners.sap.Sap'>


-------------
Rules Tested:
-------------
telemetry.rules.plugins.sap.sap_compat_issue.report
---------------------------------------------------
{'reason': 'MISSING_REQUIREMENTS', 'type': 'skip', 'rule_fqdn': 'telemetry.rules.plugins.sap.sap_compat_issue.report', 'details': "All: ['insights.combiners.sap.Sap']
Any: "}


*******************************
**** Counts By Return Type ****
*******************************
~~~

**Comment by bfahr** [comment]
Sample output from this PR and #1465.

[PR 1481 Output.docx](https://github.com/RedHatInsights/insights-core/files/2512521/PR.1481.Output.docx)
[PR 1465 Output.docx](https://github.com/RedHatInsights/insights-core/files/2512522/PR.1465.Output.docx)

**Comment by xiangce** [comment]
@csams @bfahr - I want to share a feedback from GSS TSE with you: Since they only care about the rules which are hit when running against an sosrepot, can we only display the hit rules by default? Or add another option to hide all the skipped rules?

**Comment by xiangce** [comment]
Cool, it looks great! Thanks @csams

**Comment by xiangce** [comment]
Something must be wrong with the Jenkins-pr-merge CI. Since the `brach` test passed, I go ahead and merge this PR.

**Pull request merged**
