### PR TITLE
Fixed a bug when parsing the status code in ntptime.

### PR DESCRIPTION
**Pull request by lonicerae**

### CODE REVIEW

**Comment by xiangce** [comment]
@lonicerae - would you please add a brief description in the git-commit message about this bugfix?

**Comment by lonicerae** [comment]
Hi @xiangce , please see the updated commit messages. Thanks.

**Comment by xiangce** [comment]
@lonicerae - good, please re-submit to the 3.x, I'm going to merge them together.

**Comment by lonicerae** [comment]
Hi @xiangce , please find the commit for 3.x here:

 - https://github.com/RedHatInsights/insights-core/pull/723

**Pull request merged**
