### PR TITLE
Added support for fingerprint response type in insights-core evaluators

### PR DESCRIPTION
**Pull request by pratikgadiya12**

### CODE REVIEW

**Comment by csams** [comment]
Hey @pratikgadiya12, after discussing this some more, we'd like fingerprint responses to go into their own section of the response at the same level as reports instead of adding a type to each report and mixing responses in the same section. Rule responses will still go in the reports section of the dictionary, and fingerprint responses should go in a sibling fingerprints section. Make sense?

**Comment by pratikgadiya12** [comment]
@csams : Make sense, I have updated PR. Let me know if this is what you were trying to suggest

**Comment by csams** [comment]
@pratikgadiya12, looks good to me!

**Comment by pratikgadiya12** [comment]
@csams : Thanks for the review. It seems like I don't have access to merge pull request.
Could you merge this pull request? Thanks in advance

**Pull request merged**
