### PR TITLE
tomcat_web_xml at 100% code coverage in tests

### PR DESCRIPTION
**Pull request by PaulWay**
Adding test for missing 'session-timeout' value to test other value setting branch path.

### CODE REVIEW

**Comment by PaulWay** [comment]
OK, that's weird - why is Travis reporting flake8 errors when I'm not seeing any in my local testing?

**Comment by xiangce** [comment]
@PaulWay - I can also reproduce the flake8 issue on my environment. You'd better use another branch name and do not use `.py` at the end, otherwise, the git-references of this branch will be treated as a `python` file and will be checked by flake8.

**Comment by bfahr** [comment]
@PaulWay, @xiangce is correct that your branch name ending in `.py` triggered this failure.  I have changed the flake8 configuration to ignore the `.git` directory in the future but it would be better to not use `.py` in your branch name.  

@xiangce this PR is ready to merge.

**Comment by xiangce** [comment]
@PaulWay, Please re-submit this improvement to 1.x branch after this PR is merged, Thanks

**Pull request merged**
