### PR TITLE
Removing deprecated parsers for 1.x branch

### PR DESCRIPTION
**Pull request by PaulWay**
The `cpuinfo_max_freq` and `OracleConfig` parsers are deprecated and no longer in use.  They should be removed.

### CODE REVIEW

**Comment by PaulWay** [comment]
OK - can I deprecate it with #361?

**Comment by bfahr** [comment]
@PaulWay rather than add this to #361 it would be better to revise this PR once #361 has been merged.

**Comment by PaulWay** [comment]
@bfahr Sorry, yes, that's what I meant - once #361 is approved, use the `@deprecated` decorator to mark this as deprecated.

**Comment by xiangce** [comment]
Hey @PaulWay - How is it going? Is there any chance to update this PR as per your newly added "deprecated" feature?

**Comment by xiangce** [comment]
It's fixed in #732 and #733 (#823)

**Pull request closed without merging**
