### PR TITLE
refactor(client): remove hacky proxy code

### PR DESCRIPTION
**Pull request by SteveHNH**
Requests and urllib3 now support proxy authentication natively so we
don't need this proxy hack stuff anymore. Instead we can just directly
read in the proxy authentication.

The auth split from the url is left in so that debug messages can still
work without printing the authentication to the console.

Signed-off-by: Stephen Adams <stephen.adams@redhat.com>

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Complete Description of Additions/Changes:

This PR seeks to remove older code that is not required with the more recent versions of urllib3 and requests. When it was initialy written, https proxies and authentication were not directly
supported. Now they are supported so we could simplify some of this and remove the "hacks" that were put in place. 

No actual functionality is changed. Just the method for authentication on proxies.

### CODE REVIEW

**Comment by SteveHNH** [comment]
I was able to get this configured and tested locally. Looks like it does the job, so it's ready for a review. Thanks!

**Comment by ahitacat** [comment]
Sorry Stephen for the late reply, I'm taking a look at this :smile:

**Comment by SteveHNH** [comment]
@ahitacat no worries! I rebased it.

**Comment by ahitacat** [comment]
This looks really nice. Code seems to work and it removes hacky code. 
Let's wait for new tests being created (RHSMQE-4085) in our QE pipelines before merging it.

Thanks @SteveHNH for this contribution.

**Comment by ahitacat** [comment]
test me

**Comment by ahitacat** [comment]
There are some test added to our pipelines to check this change.

**Review by ahitacat — APPROVED** [review]

**Pull request merged**
