### PR TITLE
client: Include timezone in timestamp files

### PR DESCRIPTION
**Pull request by mvollmer**

### CODE REVIEW

**Comment by mvollmer** [comment]
```
insights-core/insights/client/utilities.py:51: in get_time
    return datetime.datetime.now(datetime.timezone.utc).astimezone().isoformat()
E   AttributeError: 'module' object has no attribute 'timezone'
```

Oh, does this have to work with Python 2?

**Comment by bfahr** [comment]
@mvollmer yes, this project currently supports the versions of Python that are supported on Red Hat Enterprise Linux.

**Comment by mvollmer** [comment]
@bfahr, thanks! I am on the fence now whether it is worth including the timezone.... wdyt?

**Comment by bfahr** [comment]
@gravitypriest what do you think?

**Comment by gravitypriest** [comment]
From the look of it, the only time `get_time()` is utilized is to generate timestamps for the `.registered` and `.unregistered` files. These have been deprecated for some time, and are only still utilized for Sat integration -- the content has no function, the file simply needs to "exist" or "not exist." So, IMO timezone information is not important.

**Comment by mvollmer** [comment]
> From the look of it, the only time get_time() is utilized is to generate timestamps for the .registered and .unregistered files. 

For Cockpit integration, we read a timestamp from /etc/insights-client/.lastupload (but also see #1939).

> These have been deprecated for some time, and are only still utilized for Sat integration -- the content has no function, the file simply needs to "exist" or "not exist."

Aha! So the Sat people might also be interested in #1939, right?

**Comment by mvollmer** [comment]
Let's close this.  I don't think we will actually read `.lastupload` from Cockpit ever.  Instead, we will get all local state from the `insights-client.timer` and `insights-client.servic` units.

**Pull request closed without merging**
