### PR TITLE
RHICOMPL-3862 Adjust insights-client to upload reports in the ARF format

### PR DESCRIPTION
**Pull request by Honny1**
This PR changes the format of the report that is uploaded from scan to ARF format.  ARF extends the XCCDF report with scan information such as OVAL results etc... This change has no impact on the other components.

### CODE REVIEW

**Comment by LightOfHeaven1994** [comment]
LGTM, thanks!

**Comment by skateman** [comment]
@LightOfHeaven1994 I'm a bit concerned about the speed how fast you approved this :see_no_evil: did you try to upload a report to prod and verified that everything that should be is there?

**Comment by LightOfHeaven1994** [comment]
> @LightOfHeaven1994 I'm a bit concerned about the speed how fast you approved this see_no_evil did you try to upload a report to prod and verified that everything that should be is there?

Yes, you can see report here and part of the logs confirming it was run with `-arf`
image

image

**Comment by skateman** [comment]
@ahitacat are you the right person to ask to check this? :grin: :pray:

**Comment by ahitacat** [comment]
Hi @skateman I'm not familiar with compliance code, but it seems the client works as expected. So from an `insights-client` perspective this looks good.

But I hope that this has a review from compliance team as well :smile:

**Comment by skateman** [comment]
I AM the compliance team :rofl: but I have no merge rights here :see_no_evil:

**Comment by ahitacat** [comment]
Oh me neither :rofl: , I can approve and run the workflow. And if you approve it I think @xiangce can merge to be in the next release.

**Comment by sthirugn** [comment]
@koalakangaroo I think your team has merge rights for this repo? if yes, can you please get this reviewed? Thanks!

**Pull request merged**
