### PR TITLE
When missing dependencies don't collect it

### LINKED ISSUE #2459: Dependencies 'is_aws'/'is_azure' doesn't work on non-aws/non-azure system
The `insights.specs.default.DefaultSpecs.aws_instance_type` parser got the following result incorrectly from non-aws system:

```
# cat /tmp/insights-xxx-20200216034411/insights_commands/python_-m_insights.tools.cat_--no-header_aws_instance_type
Missing Dependencies:
    At Least One Of:
        insights.specs.default.DefaultSpecs.aws_instance_type
        insights.specs.insights_archive.InsightsArchiveSpecs.aws_instance_type
```
Then the `insights.parsers.aws_instance_type.AWSInstanceType` parser returns `.type` as "INSIGHTS", for all non-aws systems, which result some rules got fired incorrectly.

In fact, this spec `aws_instance_type` shouldn't be collected at all since it depends on `is_aws`:
https://github.com/RedHatInsights/insights-core/blob/0db5e8900507a6a60b58ac458a11644a8871306a/insights/specs/default.py#L100-L109

And the `is_aws` is skipped correctly:
```
# insights-cat insights.specs.default.DefaultSpecs.is_aws /tmp/insights-xxx-20200216034411
[Empty output]
```

And the dependency check works well:
```
# insights-cat insights.specs.default.DefaultSpecs.aws_instance_type /tmp/insights-xxx-20200216034411 
Missing Dependencies:
    Requires:
        insights.core.context.HostContext
        insights.specs.default.DefaultSpecs.is_aws
```
However, the spec is still collected by the client.
```
# cat /tmp/insights-xxx-20200216034411/insights_commands/python_-m_insights.tools.cat_--no-header_aws_instance_type
Missing Dependencies:
    At Least One Of:
        insights.specs.default.DefaultSpecs.aws_instance_type
        insights.specs.insights_archive.InsightsArchiveSpecs.aws_instance_type
```

It shouldn't be collected, right?

BTW, the `azure_*` and the other `aws_*` specs are also affected by this issue.

### PR DESCRIPTION
**Pull request by xiangce**
- fix #2459 
Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>

### CODE REVIEW

**Comment by xiangce** [comment]
This is related to #2459

**Comment by gravitypriest** [comment]
There's no harm in merging this but it won't really do anything. Core is not currently being used for insights collection, and the work in #2365 removes this function.

**Comment by xiangce** [comment]
@gravitypriest - This patch is trying to fix a false-positive reported by the customer: [bz-1803093](https://bugzilla.redhat.com/show_bug.cgi?id=1803093). And since the new #2365 is in `WIP`, can we merge this PR first to fix the bug from the customer?

**Comment by gravitypriest** [comment]
Yeah, it'll work fine.

**Pull request merged**
