### PR TITLE
Rollback soscleaner

### PR DESCRIPTION
**Pull request by gravitypriest**
Rollback soscleaner to the version prior to commit of https://github.com/RedHatInsights/insights-core/pull/2527.

However, keep the metadata ignore that was added after the fact.

### CODE REVIEW

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Review by subpop — APPROVED** [review]

**Pull request merged**
