### PR TITLE
fix: do not download uploader.json when core_collect=True

### PR DESCRIPTION
**Pull request by xiangce**
- uploader.json is not used by core collection anymore
- map the `rm_conf` from the components in memory directly
- for details, see INSGHTCORE-229 and RHELPLAN-119003

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

*Add your description here*

### CODE REVIEW

**Comment by xiangce** [comment]
@ryan-blakley and @ahitacat - I just modified the implementation, removed the `util/blacklist.py` and changed to use the `XxProvider`s own method to skip the `files/commands`. And I will add corresponding tests soon tomorrow. Please hold on the review of this PR. Sorry for the inconvenience.

**Comment by xiangce** [comment]
Test added, @ryan-blakley and @ahitacat - please kindly review when free. Thanks.

**Comment by xiangce** [comment]
The original test against the `uploader.json` file in the `test_map_components.py` was moved the a new `test_uploader_json.py` test module in another PR #3899

**Review by ryan-blakley — APPROVED** [review]
Everything looks good to me.

**Comment by xiangce** [comment]
@ryan-blakley - Thanks very much for reviewing.

**Comment by ahitacat** [comment]
test me

**Comment by xiangce** [comment]
@ahitacat - Sure, thanks for the review and reminder. I'll ask the QE team to update the IQE plugins to latest and merger this PR only when the tests are PASSED.

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
@ahitacat the IQE test passed, I'll go ahead and remove the WIP label and merge this PR.

**Pull request merged**
