### PR TITLE
xinetd.conf spec needs to match PatternSpec with xinetd.d for 1.x branch

### PR DESCRIPTION
**Pull request by PaulWay**
Otherwise this will hit the spec mismatch handling problem.

All plugin tests pass.

### CODE REVIEW

**Comment by bfahr** [comment]
@PaulWay I assume this is related to #14 and the fact that these two specs are stacked for the `XinetdConf` parser?

**Comment by PaulWay** [comment]
@bfahr Yep, correct.

**Comment by PaulWay** [comment]
@xiangce That is a much better idea - will do!

**Comment by kylape** [comment]
I'm pushing a fix directly to master (due to pending release) to fix this spec:

    PatternSpec(r"etc/xinetd\.d/.*")

The backslash in `xinetd\.d` is not interpreted as a regular expression and thus will not match anything.

**Pull request merged**
