### PR TITLE
Host and datetime parsing for ForemanSSLAccessLog

### PR DESCRIPTION
**Pull request by Rohan21Lobo**
Signed-off-by: Rohan Arora <roarora@redhat.com>

**Please do not include links to any websites that are not publicly accessible. You may include non-link reference numbers to help you and your team identify non-public references.**

### All Pull Requests:

* [x] Have you followed the guidelines in our Contributing document?
* [ ] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Issue/Bug Fix:
Provide complete details of the issue and how this PR fixes the issue. You can link to one or more existing open, publicly-accessible issue(s) that provide details.

### Enhancement:
Provide complete details of the enhancement.

Log format refferred from documentation https://httpd.apache.org/docs/2.4/logs.html

### CODE REVIEW

**Review by xiangce — COMMENTED** [review]
@Rohan21Lobo - Your update looks good. But this spec is still not added to the "uploader.json" which means it cannot be collected by the old collection. Rules will not hit, If it's used in Adviosor rules. But it's OK to use it in the GSS rules.

**Comment by Rohan21Lobo** [comment]
> @Rohan21Lobo - Your update looks good. But this spec is still not added to the "uploader.json" which means it cannot be collected by the old collection. Rules will not hit, If it's used in Adviosor rules. But it's OK to use it in the GSS rules.

@xiangce works for me, This change is anyways needed for a gss rule.

**Review by xiangce — CHANGES_REQUESTED** [review]
@Rohan21Lobo - Thanks for the response.

To make sure the core could locate the file successfully from the sos-report archives, please add the spec (simple_file) to the sos_archive.py file.

**Review by xiangce — APPROVED** [review]
@Rohan21Lobo - My mistake, it's already added to the sos_archive.py

**Pull request merged**
