### PR TITLE
Add RHSM (Red Hat Subscription-Manager) Parser

### PR DESCRIPTION
**Pull request by lveyde**
Signed-off-by: Lev Veyde <lveyde@redhat.com>

### CODE REVIEW

**Comment by xiangce** [comment]
@lveyde - As you might notice, there is an existing parser [YumRepoList](https://github.com/RedHatInsights/insights-core/blob/900148134a25d4bbaed17455dd63171667dcc64d/insights/parsers/yum.py#L44) which parses the output of `yum -C --noplugins repolist` command and can achieve the same function with this one.

https://github.com/RedHatInsights/insights-core/blob/900148134a25d4bbaed17455dd63171667dcc64d/insights/parsers/yum.py#L44

It's not suggested to add duplicated parsers. may I know the reason to add this spec and parser? Can the `YumRepoList` work for you?

**Comment by lveyde** [comment]
Hey,

The difference is that my parser takes the information directly from
subscription-manager and thus allows to properly check the available RHN
channels versus similarly named Yum repos, that may or may not include the
expected packages.

We basically need to check that customers machine is properly configured as
far as the RHN channels are concerned, and simply checking Yum doesn't
provide that accuracy.

The attempt was made to use the same rule interface as the Yum parser, so
that the rules could be easily modified to switch between parsers, if more
strict or less strict check is required.

Thanks in advance,
Lev Veyde,

**Comment by bfahr** [comment]
@lveyde you will need to get this spec approved before we add the parser.

**Comment by xiangce** [comment]
Closing it for now, please re-open it when necessary

**Pull request closed without merging**
