### PR TITLE
feat: New spec "/etc/lvm/devices/system.devices" and parser

### PR DESCRIPTION
**Pull request by huali027**
Signed-off-by: Huanhuan Li <huali@redhat.com>

### All Pull Requests:

1. Add the parser in lvm.py
2. The doc examples aren't tested before, I add the doc test to test the new parser, and also update the doc examples to make it pass.

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### CODE REVIEW

**Comment by psachin** [comment]
@huali027 You also need to add specs in `insights/specs/insights_archive.py`

**Comment by huali027** [comment]
> @huali027 You also need to add specs in `insights/specs/insights_archive.py`

@psachin, this is a file, so we don't need to add it in `insights/specs/insights_archive.py`.

**Comment by psachin** [comment]
> > @huali027 You also need to add specs in `insights/specs/insights_archive.py`
> 
> @psachin, this is a file, so we don't need to add it in `insights/specs/insights_archive.py`.

Oh. yes!

**Review by xiangce — CHANGES_REQUESTED** [review]
@huali027 - the PR looks good.

But besides the new Parser, you also updated the test of examples for some existing parsers in the file. Please describe them a bit in the PR. Thanks.

**Comment by huali027** [comment]
@xiangce, yes, I added it in the commit-msg. Let's add it manually in the first comment.

**Review by xiangce — APPROVED** [review]

**Review by psachin — APPROVED** [review]

**Pull request merged**
