### PR TITLE
Replace “cloud.redhat.com” with “console.redhat.com”

### PR DESCRIPTION
**Pull request by strider**
### All Pull Requests:

Check all that apply:

* [X] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [X] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=2006386 by replacing all string occurrences of "cloud.redhat.com" with "console.redhat.com".

### CODE REVIEW

**Review by bfahr — APPROVED** [review]

**Comment by subpop** [comment]
Do we know if we are ready to change the API URLs to console.redhat.com?

**Comment by ahitacat** [comment]
Why this is not a constant?

**Comment by subpop** [comment]
> Why this is not a constant?

The API URL is a config option (`base_url` I think). But all these random strings are not a single constant because (my guess is)  no one assumed the base host name would ever need to be changed

**Comment by xiangce** [comment]
Hi @subpop and @ahitacat, I was trying to merge this PR since Bob has approved it. However, since you are also requested for the review, May I have your approvals before merging it? Thanks.

**Review by ahitacat — APPROVED** [review]
LGTM

**Pull request merged**
