### PR TITLE
fix: obfuscate/redact the facts for legacy_upload=False

### PR DESCRIPTION
**Pull request by xiangce**
- RHINENG-8790

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

- fix the issue of RHINENG-8772 and RHINENG-7793

### CODE REVIEW

**Review by JoySnow — APPROVED** [review]

**Comment by xiangce** [comment]
@Glutexo and @ptoscano - please kindly review

**Comment by m-horky** [comment]
I am not able to reproduce the original issue.

1. Run an `ubi9` container
2. Register with subscription-manager
3. Install insights-client
4. Set `obfuscate=True`, `obfuscate_hostname=True`, `legacy_upload=False` in its config file
5. Register with insights-client
6. Ensure Inventory contains obfuscated values instead of the actual hostname/fqdn
7. Add the system to Compliance policy
8. Run the compliance collection
9. According to the RHINENG card, Inventory should display actual hostname. I did not observe any difference there.

In the logs, I can see that collected canonical facts do not include those values:
```
2024-04-12 16:57:05,661    DEBUG insights.client.connection Canonical facts collected:
{"insights_id": "0123", "subscription_manager_id": "0123", "mac_addresses": ["00:00:00:00:00:00", "32:a3:07:01:23:45"], "branch_info": {"remote_branch": -1, "remote_leaf": -1}, "satellite_id": -1}
```
```
$ insights-client --version
Client: 3.2.2
Core: 3.3.17-1
```

Am I missing some steps there?

**Comment by xiangce** [comment]
I'm not sure if your steps are the same as the customers mentioned in the cases. I can always reproduce it (w/o this change) on my VMs before adding it to the complaince as below:
```
[root@rhel9-vm ~]# insights-client --unregister
This host is not registered, unregistration is not applicable.
[root@rhel9-vm ~]# egrep "legacy_upload|^obfuscate" /etc/insights-client/insights-client.conf
obfuscate=True
obfuscate_hostname=True
legacy_upload=False
[root@rhel9-vm ~]# insights-client --register --verbose | grep "Canonical facts" -A 1
2024-04-15 11:16:50,324    DEBUG insights.client.connection Canonical facts collected:
{"insights_id": "35251d4c-a43a-495a-b85c-5b73ca277d79", "machine_id": "3095c32d-6f31-4450-9e70-629ccd7d6e21", "bios_uuid": "0b867d09-0a41-8249-8bc6-a7c6b0adb7b2", "subscription_manager_id": "35251d4c-a43a-495a-b85c-5b73ca277d79", "ip_addresses": ["192.168.0.101", "172.17.0.1", "172.18.0.1"], "mac_addresses": ["02:42:97:06:91:32", "02:42:8e:a6:7f:9e", "08:00:27:6f:ab:df", "00:00:00:00:00:00"], "fqdn": "rhel9-vm", "display_name": "rhel9-fake", "branch_info": {"remote_branch": -1, "remote_leaf": -1}, "satellite_id": -1}
```
The appearance of this issue is that the "canonical facts" is uploaded/passed to the Insights API without obfuscation. I don't know much about how the Inventory process/leverage the "metadata (canonical_facts)" when `legacy_upload=False` for the general Insights archives collected for Advisor. Because the required `facts` are also collected in the Advisor archives which were already obfuscated, I doubt the Inventory may get these facts e.g. the obfuscated-hostname already from the archive uploaded last time instead of the "metadata" in the post headers passed to the API for `compliance`. But I can indeed see the hostname in the above log, that they (includes the IPs) are not obfuscated.

Back to your test
> {"insights_id": "0123", "subscription_manager_id": "0123", "mac_addresses": ["00:00:00:00:00:00", "32:a3:07:01:23:45"], "branch_info": {"remote_branch": -1, "remote_leaf": -1}, "satellite_id": -1}
It seems there is no "hostname" or "ip_address" in the facts. As the hostname and ip_address are gotten from command `hostname` and `hostname -I`, could you please check if the `hostname` command is available or not in the container?

**Comment by xiangce** [comment]
Hmm... just realize that you have checked in Inventory and make sure the hostname is obfuscated. so the `hostname` may work well. But it looks a bit strange to me that there is no `hostname` and `ip_addresses` keys in the facts reported by the logger.debug

**Review by m-horky — APPROVED** [review]
You are right, I was missing the `hostname` package. After installation, the problem appeared, and the PR solves it. LGTM.

**Comment by xiangce** [comment]
@m-horky - Thanks for reviewing!

**Pull request merged**
