### PR TITLE
New specs var_log_pcp_openmetrics_log

### PR DESCRIPTION
**Pull request by mohitkumarrh**
Signed-off-by: Mohit Kumar <mohikuma@REDHAT.COM>

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

*Add your description here*

### CODE REVIEW

**Comment by mohitkumarrh** [comment]
py.test:
```
➜  insights-core git:(specs_var_log_pcp_openmetrics_log) ✗ py.test -svk pcp_openmetrics_log --cov=insights.parsers.pcp_openmetrics_log
=========================================================================== test session starts ===========================================================================
platform darwin -- Python 3.9.1, pytest-7.1.2, pluggy-1.0.0 -- /Users/mohitkumar/.pyenv/versions/3.9.1/bin/python3.9
cachedir: .pytest_cache
rootdir: /Users/mohitkumar/Insights/insights-core, configfile: setup.cfg, testpaths: insights
plugins: cov-3.0.0
collecting 186 items                                                                                                                                                      Downloading a fresh and hot uploader.json...
collected 2942 items / 2940 deselected / 2 selected                                                                                                                       

insights/tests/parsers/test_pcp_openmetrics_log.py::test_pcp_openmetrics_log PASSED
insights/tests/parsers/test_pcp_openmetrics_log.py::test_documentation PASSED

---------- coverage: platform darwin, python 3.9.1-final-0 -----------
Name                                      Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------------
insights/parsers/pcp_openmetrics_log.py       5      0      2      0   100%
-------------------------------------------------------------------------------------
TOTAL                                         5      0      2      0   100%


=================================================================== 2 passed, 2940 deselected in 6.71s ====================================================================

```

**Comment by mohitkumarrh** [comment]
@xiangce @psachin please review

**Comment by psachin** [comment]
@mohitkumarrh Looks good to me.

**Review by psachin — APPROVED** [review]

**Comment by psachin** [comment]
/ Pending specs approval /

**Comment by mohitkumarrh** [comment]
[insights-release-eng](https://gitlab.cee.redhat.com/insights-release-eng) PR: https://gitlab.cee.redhat.com/insights-release-eng/insights-core-assets/-/merge_requests/486

**Review by xiangce — APPROVED** [review]

**Pull request merged**
