### PR TITLE
fix(yum_updates): releasever and basearch

### PR DESCRIPTION
**Pull request by vkrizan**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

Take releasever and basearch from dnf config substitutions after loading them from variables.  It utilizes dnf.cli to load vars correctly.

RHINENG-985

### CODE REVIEW

**Comment by vkrizan** [comment]
@MichaelMraka please review

**Comment by vkrizan** [comment]
@xiangce hi, do you know where we can find the test failures?

**Comment by xiangce** [comment]
@vkrizan - Currently, these tests from `perf-scale-team` can be ignored, and the Insights-QE is the pipeline deployed on Internal Jenkins, sometimes failures occur due to ENV/network issues, it can be ignored most time. So it's Okay if the 5 `Required` Tests got Passed.

**Review by MichaelMraka — APPROVED** [review]

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
test me

**Comment by xiangce** [comment]
test me

**Comment by vkrizan** [comment]
@xiangce can you please PM me the link to "Insights-QE" Jenkis job?

**Comment by xiangce** [comment]
@vkrizan - no worries, I just tried to check if some failed cases caused by ENV can be passed. It's Okay now, since for different running it failed in different cases. I merged it.

**Pull request merged**
