### PR TITLE
Updated specs as per the specs has been generated

### PR DESCRIPTION
**Pull request by vishwanathjadhav**
https://github.com/RedHatInsights/insights-core/issues/2746

### CODE REVIEW

**Comment by vishwanathjadhav** [comment]
@xiangce, @bfahr - Please review the specs change

**Comment by xiangce** [comment]
@vishwanathjadhav - This is not an issue of insights-core but an issue of the uploader.json. Please fix it in the insights-core-assets repo.

**Comment by vishwanathjadhav** [comment]
The issue is fixed in uploader.json file

**Comment by vishwanathjadhav** [comment]
The issue is fixed in uploader.json

**Pull request closed without merging**
