### PR TITLE
Raise ParseException instead of ValueError

### PR DESCRIPTION
**Pull request by xiangce**
- for empty content and other invalid JSON content

### CODE REVIEW

**Comment by xiangce** [comment]
@bfahr - I'm a little confused, do you think this is necessary?

**Comment by bfahr** [comment]
@xiangce not I do not believe it is necessary if all you are doing is adding a try/except around the entire method.  Any exceptions are caught by the infrastructure.  We may need to have a broader discussion about this however.

**Comment by bfahr** [comment]
@csams @kylape related to exception discussion in #1040

**Comment by xiangce** [comment]
Close this PR as per the discussion with NA members.

**Pull request closed without merging**
