### PR TITLE
Remove unused collect vars

### PR DESCRIPTION
**Pull request by Glutexo**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Complete Description of Additions/Changes:

_pconn_ argument is not used. _output_ variable is initialized later.

### CODE REVIEW

**Comment by patchkez** [comment]
test this please

**Review by subpop — COMMENTED** [review]
Could we go one step further and remove `pconn` from the return value of the `collect_args` function? If its not used anywhere outside that function, then there's no reason to return it from the function call, correct?

**Review by ahitacat — APPROVED** [review]

**Comment by Glutexo** [comment]
> Could we go one step further and remove `pconn` from the return value of the `collect_args` function? If its not used anywhere outside that function, then there's no reason to return it from the function call, correct?

I already did that here: https://github.com/RedHatInsights/insights-core/pull/3284/files#diff-e731efc3c6c2617ca9bcfbfa3cf0d9672e0320032b59f7b9f6139c3e0d4a05c7L34

**Review by subpop — APPROVED** [review]

**Comment by patchkez** [comment]
test this please

**Comment by Glutexo** [comment]
RHEL 6 QE tests are still broken. I believe this is safe to merge nevertheless. cc @patchkez

**Pull request merged**
