### PR TITLE
add in gpg sig to installation and rotation

### PR DESCRIPTION
**Pull request by brantleyr**

### CODE REVIEW

**Comment by kylape** [comment]
Can you rebase against master?  Also, do you think we could factor out the common pieces between `fetch_core` and `fetch_core_sig`?

**Comment by kylape** [comment]
Note that I don't think we have to do the refactoring in this PR, just curious if you think it's feasible.

**Comment by brantleyr** [comment]
@kylape conflicts resolved, will investigate refactoring.

**Comment by brantleyr** [comment]
This PR never happened.

**Pull request closed without merging**
