### PR TITLE
Test IP obfuscation

### PR DESCRIPTION
**Pull request by Glutexo**
The soscleaner module has currently no tests. Added some for its [_\_sub\_ip_](https://github.com/RedHatInsights/insights-core/blob/d00adf50d498289b5c51dd58cdfca4ca1ce7f11f/insights/contrib/soscleaner.py#L194) method that obfuscates IP addresses. The _xfail_ marked test demonstrates how the IP obfuscation incorrectly matches an RPM package version consisting of four numbers separated by a dot.

Triggered by [ESSNTL-444](https://issues.redhat.com/browse/ESSNTL-444).

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Complete Description of Additions/Changes:

*Add your description here*

### CODE REVIEW

**Review by subpop — APPROVED** [review]
Nice. Excellent covering the tests before fixing them. Also, finally legible, table-driven tests! I approve.

**Comment by subpop** [comment]
test this please

**Comment by clarabez** [comment]
Hi, there!
We've identified that setup pipeline is failing for RHEL6 on "QE Pull Request Testing", but it is working as expected for RHEL79, RHEL84 and RHEL90.

This issue has been reported and is being analyzed here: [RHCLOUD-17392](https://issues.redhat.com/browse/RHCLOUD-17392).

**Comment by ahitacat** [comment]
Nice tests.

**Review by ahitacat — APPROVED** [review]

**Comment by Glutexo** [comment]
I manually verified the new test file on Python 2.6. Our unit tests shouldn’t affect _QE Pull Request Testing_. I believe this is safe and thus merging despite the failing task.

**Pull request merged**
