### PR TITLE
feat(compliance): RHINENG-8964 allow listing/assigning policies

### PR DESCRIPTION
**Pull request by xiangce**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Complete Description of Additions/Changes:

- This is a draft re-implementation of #4056 based on #4124

### CODE REVIEW

**Comment by skateman** [comment]
Thank you @xiangce, I will go through this after my PTO.

**Comment by romanblanco** [comment]
@xiangce @skateman is this ready to be merged?

**Comment by skateman** [comment]
We have performance issues...

**Review by LightOfHeaven1994 — APPROVED** [review]

**Comment by xiangce** [comment]
@LightOfHeaven1994 and @Mishrasubha has helped verified this PR on local, we are good to merge this PR now.

And FYI, it will be released to PyPI next Thu, it will be available for customer to use the next next Monday.

**Pull request merged**
