### PR TITLE
Core collection, final draft (WIP)

### PR DESCRIPTION
**Pull request by gravitypriest**
Took a slightly different approach than the previous PR, trying to focus on a simpler drop-in for the core collection functionality and leave our archive logic as untouched as possible. Unnecessary files have been removed. InsightsSpecs are gone, uploader.json functions, vars, and config opts are gone, all collection logic removed from the client code itself and replaced with a call to insights.collect.collect().

### Summary of Changes
- Use `insights.collect` to interface with core as the data collector
- Remove the classic data collection code
- Remove all uploader.json updating code
- Delete `insights_spec.py`
- Remove references to uploader.json files in /etc/insights-client
- Retool InsightsArchive to initialize with a `None` collected data path, and update it with the path generated by `insights.collect.collect()`
- Remove classic archival functions that add data to the archive
- Create --list option to show all commands/files run by insights-core
- Apply insights-client blacklist to core if insights-client is running the collection
- Disable components based on client blacklist
- Separate regex pattern matching and plain string pattern matching in the core blacklist chain
- Move `.exp.sed` password hiding regex to a new utility function, and pass that into core as part of the blacklist chain
- Migrate commands/files specified in remove.conf to insights-core components
- Include a copy of uploader.json in the package for remove.conf migration
- Disable parallel processing in the default manifest because multithreading is broken on RHEL 8
- Add some additional logging
- Delete unused unit tests

### Potential TODOs
- Move pattern/password redaction to after collection (like a soscleaner step)
- Convert the included uploader.json file to a simpler file to map commands to symbolic names as K/V pairs

### CODE REVIEW

**Comment by gravitypriest** [comment]
TODO: fix or remove unit tests

**Comment by gravitypriest** [comment]
test this please

**Comment by cmoore-redhat** [comment]
Hi @csams & @bfahr - Just wanted to nudge this and see if you all could provide a review for @gravitypriest when you have a chance.  Thanks!

**Comment by fstavela** [comment]
test this please

**Comment by gravitypriest** [comment]
Closed in favor of the numerous PRs that were done to release core collection.

**Pull request closed without merging**
