### PR TITLE
Enhance parser for rabbitmq_report

### PR DESCRIPTION
**Pull request by JoySnow**
1. Fix the issue occurs when handling '\n' in content.
    When the '\n' is read from archive-files, it means letters ('\\', 'n'),
    and when from local test-data variables, it will be treated as 'a-new-line'.
    Base on these, the parsing failed toward archive-files.
    To fix this issue, let 'value_tword' can also cover letter '\'.
  2. Remove the hiding of parsing errors for friendly debug usage.

Signed-off-by: XiaoXue Wang <xiaoxwan@redhat.com>

### CODE REVIEW

**Comment by xiangce** [comment]
@JoySnow - Is it related to #1906?

**Comment by JoySnow** [comment]
@xiangce  Yes. Resolve https://github.com/RedHatInsights/insights-core/issues/1906.

**Comment by xiangce** [comment]
It breaks the test of some rule related to `rabbitmq`, please have a check

**Comment by JoySnow** [comment]
@xiangce  The broken rule related to this parser is enhanced. No other rules are affected in our repos.

**Pull request merged**
