### PR TITLE
test: remove py2.6 from CI/CD test

### PR DESCRIPTION
**Pull request by xiangce**
- RHEL 6 is fully EOL, remove the test of py2.6
- Update the action versions

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

*Add your description here*

### CODE REVIEW

**Comment by xiangce** [comment]
Test of `py3.12` need more changes, and will be raised in another PR.

**Comment by chenlizhong** [comment]
@xiangce  Do we need to remove the line "'Programming Language :: Python :: 2.6'," in setup.py  ?

**Comment by xiangce** [comment]
> @xiangce Do we need to remove the line "'Programming Language :: Python :: 2.6'," in setup.py ?

@chenlizhong - I think we can keep it for a while, at least for now, it's able to run the core in py26. How about removing it when we clearly know that it totally can not be run with py26?

**Comment by chenlizhong** [comment]
@xiangce  It is best to remove the support info when removing the pipeline for 2.6 as all later MRs  are not verified by python 2.6

**Comment by xiangce** [comment]
@chenlizhong - Removing this line means that we do not support py26 anymore, I don't think it's time for us to announce that the insights-core will no longer support python 2.6. 

Here this PR is just a  workaround to ignore the env building failure in the pipeline test of py26 see https://github.com/RedHatInsights/insights-core/actions/runs/9790313689/job/27031670801?pr=4139

I can close it if insist on removing this line in this PR.

**Pull request closed without merging**
