### PR TITLE
Add scheduler spec also for Insights archive

### PR DESCRIPTION
**Pull request by skontar**

### CODE REVIEW

**Comment by skontar** [comment]
https://gitlab.cee.redhat.com/insights-release-eng/insights-core-assets/-/merge_requests/208

**Comment by bfahr** [comment]
@skontar these changes look good pending approval of the spec change.  Would you mind to review the tests for the parser and update them if you believe they are insufficient.  I've opened an issue #2997 to add documentation to the parser.

**Comment by skontar** [comment]
@bfahr Yeah, I am thinking about reworking the parser a bit, maybe even storing unused scheduler values, so it is easier to recommend different value if change is needed.

**Review by xiangce — APPROVED** [review]
Approved pending Spec

**Pull request merged**
