### PR TITLE
fix: remove the mounts combiner

### PR DESCRIPTION
**Pull request by chenlizhong**
The mounts combiner has one performance issue for IBM gpfs running hosts. As this combiner is not necessary, remove it by this MR. Use parsers.mount when you need mount information.

Signed-off-by: Chen lizhong <lichen@redhat.com>

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Complete Description of Additions/Changes:
To fix the issue: https://github.com/RedHatInsights/insights-core/issues/3610
After review the mount parser and combiner, decide to remove this combiner. Just using the corresponding parser is enough.

### CODE REVIEW

**Comment by chenlizhong** [comment]
@xiangce @psachin 
As the the ubuntu-latest has issue, change it to unbuntu-22.04,  now all tests are pass. Please review.
https://github.com/actions/setup-python/issues/162

**Comment by xiangce** [comment]
> @xiangce @psachin As the the ubuntu-latest has issue, change it to unbuntu-22.04, now all tests are pass. Please review. [actions/setup-python#162](https://github.com/actions/setup-python/issues/162)

@chenlizhong - nice catch. But please fix this issue in another new PR but do not mix it in this PR with the combiner. Thanks.

**Comment by psachin** [comment]
@chenlizhong How about we mark this for deprecation [1] and remove this after 3.1.25?

[1] https://insights-core.readthedocs.io/en/latest/api.html?highlight=deprecate#feature-deprecation

**Comment by chenlizhong** [comment]
@psachin 
Yes, before removing this, we should deprecate it to aware all users. I will keep this and raise one new MR to deprecate.

**Comment by xiangce** [comment]
@chenlizhong @psachin - Not required. This is to fix a bug that is heavily time-consuming on the host. I think it's Okay to remove it directly and skip the deprecation

**Comment by xiangce** [comment]
@chenlizhong - I'd like to leave it to you. If you don't think the `time-consuming` issue is urgent, please follow the suggestion from @psachin, deprecate it for now, and remove it from the future version `3.1.25`

**Comment by chenlizhong** [comment]
@xiangce @psachin  As the issue is performance issue, not blocking issue, my final decision is to deprecate first, then remove this from version 3.1.0.  I think version 3.1.25 is too far from today.

**Comment by xiangce** [comment]
@chenlizhong - Do you want to leave this PR here until `3.2.0` or close and reopen it when reaching `3.2.0`

**Comment by chenlizhong** [comment]
@xiangce  let us keep this and merge this in 3.2.0

**Review by xiangce — APPROVED** [review]
3.2.0 was released. let's move this forward.

**Pull request merged**
