### PR TITLE
RHCLOUD-8745 Fix warning when skipping a glob

### PR DESCRIPTION
**Pull request by Glutexo**
Fixed the bug and added some tests. The affected message is only one of a few more that serve the same purpose. I added tests for the sister warns too, so they are all covered. Used mocks to avoid relying on real files being present and possibly running into permission issues.

To reproduce:
1. Add a rule to _remove.conf_ to remove a file that would be matched by a glob rule. E.g. _/etc/yum.repos.d/redhat.repo_.
   ```ini
   [remove]
   files=/etc/yum.repos.d/redhat.repo
   ```
2. Run the client and see that a warning is emitted. This warning contains a file name and not a full specification dictionary dump.
   ```
   WARNING: Skipping file /etc/yum.repos.d/redhat.repo
   ```

### CODE REVIEW

**Comment by Glutexo** [comment]
Fixed the DCO failure. Going to add some tests.

**Review by gravitypriest — APPROVED** [review]

**Comment by Glutexo** [comment]
The _default_ check failed. I am pretty positive that this is a bug in the pipeline.

```
python /var/lib/jenkins/workspace/CI-PR-insights-core@libs/pipelineLibrary/resources/jenkins/cinch/engine.py destroy
Usage: engine.py [OPTIONS] COMMAND [ARGS]...

Error: No such command "destroy".
```

**Comment by gravitypriest** [comment]
test this please

**Comment by gravitypriest** [comment]
test this please

**Pull request merged**
