### PR TITLE
WIP: Integrate Jupyter notebooks into documentation

### PR DESCRIPTION
**Pull request by bfahr**
These changes integrate the build of documentation with Jupyter notebooks

* Adds new notebooks sub dir to docs
* Move existing notebook to subdir and rename to remove spaces
* Include required packages in setup
* Modify Shippable and Travis builds to support inclusion of notebooks into docs

### CODE REVIEW

**Comment by bfahr** [comment]
The tests will fail due to a bug in the `nbsphinx` package, see this bug report: https://github.com/spatialaudio/nbsphinx/issues/127

Once fix is in place tests should pass.

**Comment by csams** [comment]
@bfahr Having the notebooks in both github and the official docs is a great idea. Hopefully a new version of nbsphinx will be released soon.

I think we should also update the README to point to the individual notebooks and to the top level of the docs on rtd.

**Comment by bfahr** [comment]
@csams I've brought up to date with master and tried again with latest version of nbsphinx (0.2.15) and now we get a new error in nbsphinx that appears to be different.
```
# Sphinx version: 1.6.5
# Python version: 2.7.13 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.9.6
# Last messages:
#   Running Sphinx v1.6.5
#   making output directory...
#   building [mo]: all of 0 po files
#   building [html]: all source files
#   updating environment:
#   212 added, 0 changed, 0 removed
#   reading sources... [  0%] api
# Loaded extensions:
#   sphinx.ext.viewcode (1.6.5) from /home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.napoleon (1.6.5) from /home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/sphinx/ext/napoleon/__init__.pyc
#   sphinx.ext.todo (1.6.5) from /home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   sphinx.ext.autodoc (1.6.5) from /home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   alabaster (0.7.10) from /home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/alabaster/__init__.pyc
#   nbsphinx (0.2.15) from /home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/nbsphinx.pyc
Traceback (most recent call last):
  File "/home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_all()
  File "/home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 288, in build_all
    self.build(None, summary='all source files', method='all')
  File "/home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 584, in update
    self._read_serial(docnames, self.app)
  File "/home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 603, in _read_serial
    self.read_doc(docname, app)
  File "/home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 726, in read_doc
    pub.publish()
  File "/home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/bfahr/work/insights/insights-core/lib/python2.7/site-packages/nbsphinx.py", line 1099, in apply
    title = sig['ids'][0]
IndexError: list index out of range
```

**Comment by bfahr** [comment]
I'm going to close this and resubmit with the latest set of notebooks.

**Pull request closed without merging**
