### PR TITLE
Unitfiles parser enhanced to deal with all unit states.

### PR DESCRIPTION
**Pull request by jsvob**

### CODE REVIEW

**Comment by jsvob** [comment]
I don't understand this.

https://app.shippable.com/github/RedHatInsights/insights-core/runs/378/2/console told me "./insights/parsers/tests/test_unitfiles.py:74:56: W292 no newline at end of file". So I added exactly one newline at the end of the file and checked the diff that I added just one new line.

Then https://app.shippable.com/github/RedHatInsights/insights-core/runs/386/2/console told me "./insights/parsers/tests/test_unitfiles.py:75:1: W391 blank line at end of file".

@kylape Any idea how to fix it, please?

**Comment by bfahr** [comment]
@jsvob when I delete the last line the error goes away at my terminal.

**Comment by bfahr** [comment]
@jsvob would you mind to go ahead and add this module to the documentation by adding a `.rst` file and docstrings?

**Comment by jsvob** [comment]
@bfahr I apparently suck at using PyCharm - now I am able to resolve the flake8 issue. Thanks for trying it. I added the documentation both here and in #114.

**Comment by bfahr** [comment]
@jsvob I think pycharm complains if no blank line at the end.  Just make sure to run `flake8` before you commit.

**Pull request merged**
