### PR TITLE
Ansible playbook verifier interface

### PR DESCRIPTION
**Pull request by dehort**
This PR defines the interface for verifying the signatures on ansible playbooks

python module usage:

```
from insights.client.apps.ansible import playbook_verifier
verified_playbook = playbook_verifier.verify(signed_unverified_playbook)
``` 
An exception is raised in the case of an error. 

command line usage:

```
$ PYTHONPATH=../insights-core python/ -m insights.client.apps.ansible.playbook_verifier < TEST_PLAYBOOK.txt > stdout.txt; echo $?
0

```

The return code is zero in the happy path.  The verified playbook is written to stdout.

(unhappy path) command line usage:

```
$ ANSIBLE_PLAYBOOK_VERIFIER_THROW_ERROR=1 PYTHONPATH=../insights-core python -m insights.client.apps.ansible.playbook_verifier < TEST_PLAYBOOK.txt 2>stderr.txt; echo $?
1

```
The return code is non-zero in the unhappy path.  An error message is written to stderr.

Its also possible to use the new `--module` option on the `insights-client` to run the playbook verifier from the command line:

```
sudo PYTHONPATH=../insights-core BYPASS_GPG=True EGG=../insights-core/insights.zip ./src/insights-client --no-gpg --offline -c data/insights-client.conf --module insights.client.apps.ansible.playbook_verifier < unverified_playbook.yml > verified_playbook.yml 2>stderr.txt ; echo $?
```

[RHCLOUD-10099]

### CODE REVIEW

**Review by subpop — APPROVED** [review]

**Review by aleccohan — APPROVED** [review]
LGTM!

**Review by gravitypriest — APPROVED** [review]

**Comment by dehort** [comment]
Moved the code around so that the new `--module` option on the insights-client command line util can be used to run the playbook verifier:

`sudo  PYTHONPATH=../insights-core BYPASS_GPG=True EGG=../insights-core/insights.zip ./src/insights-client --no-gpg --offline -c data/insights-client.conf --module insights.client.apps.ansible.playbook_verifier < unverified_playbook.yml > verified_playbook.yml 2>stderr.txt ; echo $?`

**Review by gravitypriest — APPROVED** [review]

**Comment by dehort** [comment]
@subpop @gravitypriest would one of you mind to merge this?  Is there a different process that I should be following?

**Comment by gravitypriest** [comment]
Just had to catch it up with master. Will merge once checks are complete.

**Comment by gravitypriest** [comment]
Merging despite test_unregister failure - the failure is intermittent and is unrelated to this PR.

**Pull request merged**
