### PR TITLE
client: write lastupload during platform upload

### PR DESCRIPTION
**Pull request by subpop**
Write the `/etc/insights-client/.lastupload` file during platform upload too.

Fixes: RHCLOUD-8339

### CODE REVIEW

**Comment by gravitypriest** [comment]
A minor detail, but perhaps the call should be made from `insights.client.client.upload()` for parity with the `_legacy_upload` function in the same module, but I have plans to consolidate everything in the near future so this is OK.

**Comment by subpop** [comment]
Wait, I think this is being made from `insights.client.client.upload()`.

```
diff --git a/insights/client/client.py b/insights/client/client.py
index 7fd9bc59c..59292283d 100644
--- a/insights/client/client.py
+++ b/insights/client/client.py
@@ -363,6 +363,7 @@ def upload(config, pconn, tar_file, content_type, collection_duration=None):
         upload = pconn.upload_archive(tar_file, content_type, collection_duration)
 
         if upload.status_code in (200, 202):
+            write_to_disk(constants.lastupload_file)
             msg_name = determine_hostname(config.display_name)
             logger.info("Successfully uploaded report for %s.", msg_name)
             if config.register:
```

**Comment by gravitypriest** [comment]
You're right, I misread. Carry on.

**Comment by subpop** [comment]
test this please

**Pull request merged**
