### PR TITLE
fix: update OSRelease.is_rhel more accurate

### PR DESCRIPTION
**Pull request by xiangce**
- introduce the check of `dmesg`
- update the check of `uname` and `rpms`
- check the 'redhat-release' and 'os-release' only when others are all unavailable
- add new property 'reasons' that returns why it's not RHEL

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Complete Description of Additions/Changes:

- and fix incorrect reports against some NON-RHEL hosts, e.g.
   the following `os-release` should be identified as `Oracle Linux`
```
NAME="Oracle Linux Server"
ID="ol"
PRETTY_NAME="Red Hat Enterprise Linux"
```
- for more details, refer to RHINRULE-122

### CODE REVIEW

**Comment by xiangce** [comment]
@chenlizhong, @wushiqinlou, @huali027 - please kindly review.

**Review by chenlizhong — APPROVED** [review]
Looks good to me

**Comment by wushiqinlou** [comment]
@xiangce - Good to me.

**Comment by huali027** [comment]
Good to me

**Comment by chenlizhong** [comment]
test me

**Comment by xiangce** [comment]
test me

**Pull request merged**
