### PR TITLE
update test-connection option to return cleaner output

### PR DESCRIPTION
**Pull request by SteveHNH**
Changed some test-connection lines to log as debug rather than info in order to clean up the output. Mainly removes the printing of the cert to stdout, but it still logs it. This cleans the output up a
bit for a customer so they can more easily read what's going on.
```
[vagrant@ethereal7 ~]$ insights-client --no-gpg --register                                                                                                                                                                                
Insights API could not be reached to confirm registration status.                                                                                                                                                                         
Running connection test...                                                                                                                                                                                                                
Connection test config:                                                                                                                                                                                                                   
=== Begin Certificate Chain Test ===                                                                                                                                                                                                      
depth=1                                                                                                                                                                                                                                   
verify error:num=0                                                                                                                                                                                                                        
verify return:1                                                                                                                                                                                                                           
depth=0                                                                                                                                                                                                                                   
verify error:num=0                                                                                                                                                                                                                        
verify return:1                                                                                                                                                                                                                           
=== End Certificate Chain Test: SUCCESS ===                                                                                                                                                                                               
                                                                                                                                                                                                                                          
=== Begin Upload URL Connection Test ===                                                                                                                                                                                                  
HTTP Status Code: 401                                                                                                                                                                                                                     
HTTP Status Text: Unauthorized                                                                                                                                                                                                            
HTTP Response Text:                                                                                                                                                                                                                       
Connection failed                                                                                                                                                                                                                         
=== End Upload URL Connection Test: FAILURE ===                                                                                                                                                                                           
                                                                                                                                                                                                                                          
=== Begin API URL Connection Test ===                                                                                                                                                                                                     
HTTP Status Code: 200                                                                                                                                                                                                                     
HTTP Status Text: OK                                                                                                                                                                                                                      
HTTP Response Text: lub-dub                                                                                                                                                                                                               
Successfully connected to: https://cert-api.access.redhat.com/r/insights/                                                                                                                                                                 
=== End API URL Connection Test: SUCCESS ===                                                                                                                                                                                              
                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                          
Connectivity tests completed with some errors 
```

### CODE REVIEW

**Comment by kylape** [comment]
Do you think it would be helpful to give some high level info to the console?  If a user used `--test-connection` with your changes, would they see any information about the connection test on the console?

**Comment by SteveHNH** [comment]
@klape I could probably have it print out more. This basically shows the same thing it used to show, but it removes the certificate output from it. It still shows the success/fail of the cert, URL, and API tests. it also includes the status code and text for the two HTTP checks. It logs everything, including the cert, so they can check there for the rest of the data.

Here's the full output of a connection test:
```
[vagrant@rhel7-box ~]$ insights-client --no-gpg --test-connection                                                      
Connection test config:                                    
=== Begin Certificate Chain Test ===                       
depth=1                                                    
verify error:num=0                                         
verify return:1                                            
depth=0                                                    
verify error:num=0                                         
verify return:1                                            
=== End Certificate Chain Test: SUCCESS ===                

=== Begin Upload URL Connection Test ===                   
HTTP Status Code: 401                                      
HTTP Status Text: Unauthorized                             
HTTP Response Text:                                        
Connection failed                                          
=== End Upload URL Connection Test: FAILURE ===            

=== Begin API URL Connection Test ===                      
HTTP Status Code: 200                                      
HTTP Status Text: OK                                       
HTTP Response Text: lub-dub                                
Successfully connected to: https://cert-api.access.redhat.com/r/insights/                                              
=== End API URL Connection Test: SUCCESS ===               


Connectivity tests completed with some errors              
Failed connection test.  See /var/log/insights-client/insights-client.log for details.
```

**Comment by kylape** [comment]
I probably should I have just stated what I was thinking:  Adding one or two log messages in addition to all the messages you changed to debug.  Maybe something that says "Running connection tests..." and "Tests {pass|fail}.  See log for details".

**Comment by SteveHNH** [comment]
@klape oh yeah. I can definitely work that in. Thanks for the suggestion

**Pull request merged**
