### PR TITLE
Cleanup temp dir created for egg download (#2721)

### PR DESCRIPTION
**Pull request by Rohan21Lobo**
https://github.com/RedHatInsights/insights-core/issues/2721

### CODE REVIEW

**Comment by Rohan21Lobo** [comment]
I am yet to test the change but still submitting a potential MR.

Admins, feel free too suggest/add changes as this affects a customer. Or Else I will dig around how to test this over weekend.

**Comment by tentator** [comment]
up? :+1:

**Comment by patchkez** [comment]
@Rohan21Lobo Could you please rebase the PR and we will test the changes locally. Thanks.

**Comment by Rohan21Lobo** [comment]
@patchkez Rebased. I couldn't test all scenarios by playing with my environment. 
Over to you.

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
@Rohan21Lobo @subpop Looks good, I was able to build egg and perform several tests with this custom egg. However I was not able to test download of new egg as I was using custom one.

**Comment by subpop** [comment]
@gravitypriest what do you think?

**Comment by gravitypriest** [comment]
Looks good. To be honest we could probably delete the temp dir immediately after the egg is copied to /var/lib/ instead of waiting for exit, but there's no issues here. Let's get it into the next release.

**Pull request merged**
