### PR TITLE
[WIP] Add parser for JBoss domain mode config files

### PR DESCRIPTION
**Pull request by xiangce**
- From #889

### CODE REVIEW

**Comment by bfahr** [comment]
@zhangyi733 is this PR still WIP?

**Comment by xiangce** [comment]
@bfahr - Thanks for checking. 

As we talked last week, currently, we do not have a candidate plugin depends on this spec and the logic of its datasource is not finally decided yet. Let's just leave it as WIP.

Thanks.

**Comment by bfahr** [comment]
@xiangce should we continue to leave this as WIP or do you want to close and resubmit when needed?

**Comment by xiangce** [comment]
OK, I go ahead and close this PR. Since @chenlizhong takes over the JBoss SBR, I think he could resubmit it when everything is ready. Thank you @bfahr.

**Pull request closed without merging**
