### PR TITLE
fix: ensure "insights_log/lib_dir" exist when running w/ non-root user

### PR DESCRIPTION
**Pull request by xiangce**
### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

- Fix the new test issue in py3 pipeline
   The required dirs are not created for the test user.

### CODE REVIEW

**Review by chenlizhong — APPROVED** [review]
Looks good to me

**Comment by ahitacat** [comment]
I will prefer to fix this on the test rather than on code. Clearly the tests are trying to use system files but in an an unmanaged manner.

**Review by ahitacat — CHANGES_REQUESTED** [review]
I will prefer to fix this on the test rather than on code. Clearly the tests are trying to use system files but in an an unmanaged manner.

**Comment by xiangce** [comment]
@ahitacat and @DuckBoss - Thanks for looking into. Your new resolution looks better than this. Closing this one.

**Pull request closed without merging**
